import React, {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {call,callJSON,hasBridge,installNativeHooks,parseMutation,saveConfig} from './bridge.js';

const NAV=[
 {group:'概览',items:[['overview','◉','运行概览'],['devices','▱','身份与设备']]},
 {group:'网络',items:[['connection','⌁','连接与路径'],['exits','↗','出口选择'],['proxy','⇄','本机代理'],['exitshare','◇','本机出口共享']]},
 {group:'策略',items:[['routing','⑂','分流规则'],['rdp','▣','远程桌面'],['messages','✦','消息']]},
 {group:'观察',items:[['monitor','⌁','实时监控'],['diagnostics','⌘','诊断与日志']]}
];

const EMPTY={
 revision:'',serverAddress:'',quicPort:35820,tcpPort:35821,tlsEnabled:true,deviceName:'',identityId:'',transport:'auto',
 socks5:{enabled:true,listen:'127.0.0.1',port:1080},http:{enabled:true,listen:'127.0.0.1',port:8080},defaultExitId:'',
 exitEnabled:true,allowInternet:true,allowPrivateNetwork:false,allowLoopback:false,accessMode:'',accessDomains:[],accessCidrs:[],
 exitUpstream:{mode:'',address:'',username:'',password:''},
 p2p:{enabled:true,mode:'auto',punchTimeoutMs:1200,keepaliveSec:10,idleTimeoutSec:120,maxExitSessions:4,fallback:true},publicDirectAdvertise:'',
 networkMode:'',network:{mode:'',exclude_processes:[]},isAutostart:false,minimizeToTray:true,theme:'system',
 verificationPopupTimeoutSec:12,routing:{mode:'global_proxy',default_action:'PROXY',rules:[]},configPath:'',version:''
};

const cx=(...v)=>v.filter(Boolean).join(' ');
const arr=v=>Array.isArray(v)?v:[];
const split=v=>String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean);
const fmtTime=v=>{if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString()};
const fmtBytes=(v,rate=false)=>{let n=Math.max(0,Number(v)||0),i=0;const u=['B','KB','MB','GB','TB'];while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i===0?0:n>=100?0:n>=10?1:2)+' '+u[i]+(rate?'/s':'')};
const logText=v=>typeof v==='string'?v:(v&&(v.line||v.message||v.text))||JSON.stringify(v||'');
const tone=v=>{const s=String(v||'').toLowerCase();if(/active|ready|connected|online|approved|success|直连/.test(s))return'ok';if(/error|failed|reject|deny|offline|失败|拒绝/.test(s))return'danger';if(/connecting|pending|wait|准备|协商/.test(s))return'warn';return'neutral'};
const exitName=(exits,id)=>{if(!id)return'自动选择';const e=arr(exits).find(x=>(x.deviceId||x.id)===id);return(e&&(e.name||e.deviceName))||id};

function Logo(){return <div className="logo">↗</div>}
function Button({children,primary,danger,quiet,className,...p}){return <button className={cx('btn',primary&&'primary',danger&&'danger',quiet&&'quiet',className)} {...p}>{children}</button>}
function Badge({children,tone:t='neutral'}){return <span className={cx('badge',t)}>{children}</span>}
function Switch({checked,onChange,disabled,label}){return <button type="button" className={cx('switch',checked&&'on')} role="switch" aria-checked={!!checked} aria-label={label} disabled={disabled} onClick={()=>onChange&&onChange(!checked)}><span/></button>}
function Card({title,eyebrow,action,children,className}){return <section className={cx('card',className)}>{(title||eyebrow||action)&&<div className="card-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}{title&&<h2>{title}</h2>}</div>{action}</div>}{children}</section>}
function PageHead({title,desc,actions}){return <div className="page-head"><div><h1>{title}</h1>{desc&&<p>{desc}</p>}</div>{actions&&<div className="actions">{actions}</div>}</div>}
function Field({label,help,children,className}){return <label className={cx('field',className)}><span>{label}</span>{children}{help&&<small>{help}</small>}</label>}
const Input=p=><input className="control" {...p}/>;
const Select=p=><select className="control" {...p}/>;
const Textarea=p=><textarea className="control textarea" {...p}/>;
function Setting({title,desc,children}){return <div className="setting"><div className="grow"><b>{title}</b>{desc&&<div className="mini">{desc}</div>}</div>{children}</div>}
function Metric({label,value,hint}){return <div className="metric"><div className="eyebrow">{label}</div><div className="metric-value">{value}</div><div className="mini">{hint}</div><div className="spark"><i/><i/><i/><i/><i/><i/><i/></div></div>}
function Modal({open,title,children,footer,onClose,wide}){if(!open)return null;return <div className="overlay show" onMouseDown={e=>e.target===e.currentTarget&&onClose&&onClose()}><div className={cx('modal',wide&&'wide')}><div className="modal-head"><h2>{title}</h2><button className="close" onClick={onClose}>×</button></div><div className="modal-body">{children}</div>{footer&&<div className="modal-foot">{footer}</div>}</div></div>}

function Overview({status,config,exits,onSelect,onRefresh,onGoto}){
 const connected=!!status.connected,path=status.directPath||status.p2pPath||status.transport||'等待连接',rtt=status.directRttMs||status.p2pRttMs||status.latency||0;
 return <><PageHead title="运行概览" desc="当前连接、出口路径与本机代理的实时状态。" actions={<><Button onClick={onRefresh}>刷新</Button><Button primary onClick={()=>onGoto('exits')}>切换出口</Button></>}/>
 <Card className="hero"><div className="hero-glow"/><div className="hero-status"><span className={cx('dot',connected?'online':'offline')}/><div><div className="eyebrow">{connected?'CONNECTED':'DISCONNECTED'}</div><div className="big">{connected?'RelayProxy 已连接':'等待连接到 RelayProxy Server'}</div><div className="muted">{(config.serverAddress||'尚未配置服务器')+' · '+(status.transport||config.transport||'auto')}</div></div></div>
 <div className="exit-mini"><div className="flag">↗</div><div className="grow"><div className="mini">当前出口</div><strong>{exitName(exits,status.selectedExit||config.defaultExitId)}</strong><div className="mini">{path+' · '+(rtt?rtt+' ms':'等待延迟数据')}</div></div><Select value={status.selectedExit||config.defaultExitId||''} onChange={e=>onSelect(e.target.value)}><option value="">自动选择</option>{exits.map(e=><option key={e.deviceId||e.id} value={e.deviceId||e.id}>{e.name||e.deviceId}</option>)}</Select></div>
 <svg className="map-line" viewBox="0 0 520 160"><path d="M18 112 C122 40 205 138 302 68 S442 54 510 22"/><circle cx="18" cy="112" r="5"/><circle cx="302" cy="68" r="5"/><circle cx="510" cy="22" r="5"/></svg></Card>
 <div className="cards-4"><Metric label="延迟" value={(status.latency||0)+' ms'} hint="Server RTT"/><Metric label="活动连接" value={status.activeStreams||0} hint="当前转发流"/><Metric label="P2P / Direct" value={status.p2pState||status.directState||'—'} hint={status.p2pPath||status.directPath||'自动路径'}/><Metric label="透明代理" value={status.divertRunning?'已接管':'未启用'} hint={status.divertStage||config.networkMode||'off'}/></div>
 <div className="cards-2"><Card title="本机服务" eyebrow="LOCAL SERVICES"><Setting title="SOCKS5" desc={(config.socks5?.listen||'127.0.0.1')+':'+(config.socks5?.port||1080)}><Badge tone={status.socks5Running?'ok':'neutral'}>{status.socks5Running?'运行中':'已停止'}</Badge></Setting><Setting title="HTTP Proxy" desc={(config.http?.listen||'127.0.0.1')+':'+(config.http?.port||8080)}><Badge tone={status.httpRunning?'ok':'neutral'}>{status.httpRunning?'运行中':'已停止'}</Badge></Setting><Setting title="出口共享" desc="将本机作为授权网络出口"><Badge tone={status.exitRunning?'ok':'neutral'}>{status.exitRunning?'正在共享':'未运行'}</Badge></Setting></Card>
 <Card title="身份状态" eyebrow="IDENTITY"><Setting title={status.deviceName||config.deviceName||'本设备'} desc={status.deviceId||'等待设备 ID'}><Badge tone={tone(status.approvalState)}>{status.approvalState||'未知'}</Badge></Setting><Setting title="身份" desc={status.identityName||config.identityId||'尚未绑定'}><span className="mono">{status.policyRevision?'策略 r'+status.policyRevision:'—'}</span></Setting><Setting title="运行模式" desc="由 Server 授权能力决定"><Badge tone="blue">{status.mode||'CLIENT'}</Badge></Setting></Card></div></>
}

function Devices({status,config,setv,save}){
 return <><PageHead title="身份与设备" desc="设备身份由 Server 审批并控制可用能力；此处管理本机标识与连接身份。"/><div className="cards-2"><Card title="设备状态" eyebrow="DEVICE"><div className="identity-tile"><div className="identity-icon">▱</div><div className="grow"><div className="big small-big">{status.deviceName||config.deviceName||'RelayProxy Device'}</div><div className="mono muted">{status.deviceId||'等待 Server 分配设备 ID'}</div></div><Badge tone={tone(status.approvalState)}>{status.approvalState||'待连接'}</Badge></div><div className="divider"/><Setting title="身份名称" desc="当前身份隔离范围">{status.identityName||'—'}</Setting><Setting title="策略版本" desc="Server 下发的权限策略">{status.policyRevision||'—'}</Setting><Setting title="当前模式" desc="CLIENT / EXIT / BOTH"><Badge tone="blue">{status.mode||'—'}</Badge></Setting></Card>
 <Card title="本机身份配置" eyebrow="CONFIGURATION"><div className="form-grid"><Field label="设备名称"><Input value={config.deviceName||''} onChange={e=>setv('deviceName',e.target.value)}/></Field><Field label="身份 ID" help="由 Server 创建的身份 ID。"><Input value={config.identityId||''} onChange={e=>setv('identityId',e.target.value)}/></Field><Field label="Server 地址" className="full"><Input value={config.serverAddress||''} onChange={e=>setv('serverAddress',e.target.value)}/></Field></div><div className="actions end"><Button primary onClick={()=>save({device:{name:config.deviceName,identityId:config.identityId},server:{address:config.serverAddress}})}>保存身份配置</Button></div></Card></div><Card title="审批说明" eyebrow="SERVER AUTHORIZATION"><div className="notice">设备首次连接后需要在 Server 管理端审批。出口、RDP、消息渠道等能力均按身份与设备授权隔离，客户端不会展示未授权资源。</div></Card></>
}

function Connection({status,config,setv,save}){
 const p=config.p2p||EMPTY.p2p;
 return <><PageHead title="连接与路径" desc="控制 QUIC/TCP 传输偏好、P2P 与公网直连策略，并观察实时路径。"/><div className="cards-3"><Card title="当前传输"><div className="big small-big">{status.transport||'—'}</div><div className="mini">Server RTT {status.latency||0} ms</div></Card><Card title="Direct Path"><div className="big small-big">{status.directState||'idle'}</div><div className="mini">{status.directPath||status.directEndpoint||'未建立'}</div></Card><Card title="P2P"><div className="big small-big">{status.p2pState||'idle'}</div><div className="mini">{status.p2pPath||status.p2pCandidateSummary||'自动协商'}</div></Card></div>
 <Card title="服务器与端口" eyebrow="SERVER"><div className="form-grid"><Field label="Relay Server"><Input value={config.serverAddress||''} onChange={e=>setv('serverAddress',e.target.value)}/></Field><Field label="TLS"><Select value={config.tlsEnabled===false?'off':'on'} onChange={e=>setv('tlsEnabled',e.target.value==='on')}><option value="on">启用 TLS</option><option value="off">关闭 TLS</option></Select></Field><Field label="QUIC / UDP 端口"><Input type="number" value={config.quicPort||35820} onChange={e=>setv('quicPort',Number(e.target.value))}/></Field><Field label="TCP / TLS 端口"><Input type="number" value={config.tcpPort||35821} onChange={e=>setv('tcpPort',Number(e.target.value))}/></Field></div></Card>
 <Card title="传输策略" eyebrow="TRANSPORT"><div className="option-grid">{[['auto','自动','优先 QUIC，必要时回落 TCP'],['quic_only','仅 QUIC','固定使用 QUIC 传输'],['tcp_only','仅 TCP','固定使用 TLS/TCP']].map(x=><button key={x[0]} className={cx('option',config.transport===x[0]&&'selected')} onClick={()=>setv('transport',x[0])}><div><strong>{x[1]}</strong><div className="mini">{x[2]}</div></div><span className="radio"/></button>)}</div></Card>
 <Card title="Direct / P2P" eyebrow="PATH POLICY"><Setting title="启用 P2P 直连" desc="首个请求可先走 Relay，后台建立可复用直连。"><Switch checked={p.enabled!==false} onChange={v=>setv('p2p.enabled',v)}/></Setting><div className="form-grid top-gap"><Field label="路径模式"><Select value={p.mode||'auto'} onChange={e=>setv('p2p.mode',e.target.value)}><option value="auto">auto · 自动</option><option value="direct_only">direct_only · 仅公网直连</option><option value="p2p_only">p2p_only · 仅 P2P</option><option value="relay_only">relay_only · 仅 Relay</option></Select></Field><Field label="打洞超时 (ms)"><Input type="number" value={p.punchTimeoutMs??1200} onChange={e=>setv('p2p.punchTimeoutMs',Number(e.target.value))}/></Field><Field label="Keepalive (s)"><Input type="number" value={p.keepaliveSec??10} onChange={e=>setv('p2p.keepaliveSec',Number(e.target.value))}/></Field><Field label="空闲超时 (s)"><Input type="number" value={p.idleTimeoutSec??120} onChange={e=>setv('p2p.idleTimeoutSec',Number(e.target.value))}/></Field><Field label="最大出口会话"><Input type="number" value={p.maxExitSessions??4} onChange={e=>setv('p2p.maxExitSessions',Number(e.target.value))}/></Field><Field label="失败回落"><Select value={p.fallback===false?'off':'on'} onChange={e=>setv('p2p.fallback',e.target.value==='on')}><option value="on">允许回落 Relay</option><option value="off">不允许回落</option></Select></Field><Field label="手动公网地址（可选）" help="用于端口转发 / 云主机 DNS 等场景，Server 会主动验证。"><Input value={config.publicDirectAdvertise||''} onChange={e=>setv('publicDirectAdvertise',e.target.value)} placeholder="edge.example.com:35820"/></Field></div><div className="actions end top-gap"><Button primary onClick={()=>save({server:{address:config.serverAddress,quicPort:Number(config.quicPort),tcpPort:Number(config.tcpPort),tlsEnabled:config.tlsEnabled},transport:config.transport,p2p:config.p2p,direct:{public:{advertise:config.publicDirectAdvertise||''}}})}>保存连接策略</Button></div></Card>{(status.directError||status.p2pError)&&<div className="notice danger">{status.directError||status.p2pError}</div>}</>
}

function Exits({status,exits,selected,onSelect,onSpeed}){
 return <><PageHead title="出口选择" desc="仅显示 Server 授权给当前身份/设备的网络出口。" actions={<Button onClick={()=>onSpeed(selected)}>出口测速</Button>}/><div className="exit-grid"><button className={cx('exit-card',!selected&&'selected')} onClick={()=>onSelect('')}><div className="flag">◎</div><div className="grow"><strong>自动选择</strong><div className="mini">根据当前策略选择出口</div></div><span className="radio"/></button>{exits.map(e=>{const id=e.deviceId||e.id;return <button key={id} className={cx('exit-card',selected===id&&'selected',e.online===false&&'disabled')} onClick={()=>e.online!==false&&onSelect(id)}><div className="flag">↗</div><div className="grow"><div className="row"><strong>{e.name||id}</strong><Badge tone={e.online===false?'neutral':'ok'}>{e.online===false?'离线':'在线'}</Badge></div><div className="mini">{e.identityName||e.authorizationSource||id}</div></div><span className="radio"/></button>})}</div>{!exits.length&&<Card><div className="empty">当前没有已授权出口。请在 Server 管理端为此身份授权可用出口。</div></Card>}<Card title="当前路径" eyebrow="LIVE PATH"><div className="cards-3 compact"><div><div className="mini">选择出口</div><strong>{exitName(exits,selected)}</strong></div><div><div className="mini">Direct</div><strong>{status.directPath||status.directState||'—'}</strong></div><div><div className="mini">P2P</div><strong>{status.p2pPath||status.p2pState||'—'}</strong></div></div></Card></>
}

function ProxyPage({status,config,setv,save}){
 const s=config.socks5||EMPTY.socks5,h=config.http||EMPTY.http;
 return <><PageHead title="本机代理" desc="管理 SOCKS5、HTTP Proxy 与 Windows 透明代理接管。"/><div className="cards-2"><Card title="SOCKS5" eyebrow="LOCAL PROXY" action={<Switch checked={s.enabled!==false} onChange={v=>setv('socks5.enabled',v)}/>}><Badge tone={status.socks5Running?'ok':'neutral'}>{status.socks5Running?'运行中':'未运行'}</Badge><div className="form-grid top-gap"><Field label="监听地址"><Input value={s.listen||''} onChange={e=>setv('socks5.listen',e.target.value)}/></Field><Field label="端口"><Input type="number" value={s.port||1080} onChange={e=>setv('socks5.port',Number(e.target.value))}/></Field></div></Card><Card title="HTTP Proxy" eyebrow="LOCAL PROXY" action={<Switch checked={h.enabled!==false} onChange={v=>setv('http.enabled',v)}/>}><Badge tone={status.httpRunning?'ok':'neutral'}>{status.httpRunning?'运行中':'未运行'}</Badge><div className="form-grid top-gap"><Field label="监听地址"><Input value={h.listen||''} onChange={e=>setv('http.listen',e.target.value)}/></Field><Field label="端口"><Input type="number" value={h.port||8080} onChange={e=>setv('http.port',Number(e.target.value))}/></Field></div></Card></div>
 <Card title="透明代理" eyebrow="WINDOWS NETWORK CAPTURE"><Setting title="接管系统流量" desc="使用 WinDivert 将本机连接交给 RelayProxy 分流引擎。"><Switch checked={config.networkMode==='divert'} onChange={v=>{setv('networkMode',v?'divert':'');setv('network.mode',v?'divert':'')}}/></Setting><div className="notice top-gap">状态：{status.divertRunning?'已接管':'未接管'} · 阶段：{status.divertStage||'idle'}{status.divertError?' · '+status.divertError:''}</div><Field label="排除进程（每行一个）"><Textarea rows="5" value={arr(config.network?.exclude_processes).join('\n')} onChange={e=>setv('network.exclude_processes',split(e.target.value))}/></Field><div className="actions end"><Button primary onClick={()=>save({proxy:{socks5Enabled:s.enabled,socks5Listen:s.listen,socks5Port:Number(s.port),httpEnabled:h.enabled,httpListen:h.listen,httpPort:Number(h.port),defaultExitId:config.defaultExitId||''},network:{mode:config.networkMode||'',excludeProcesses:arr(config.network?.exclude_processes)}})}>保存代理设置</Button></div></Card></>
}

function ExitShare({status,config,setv,save}){
 const u=config.exitUpstream||EMPTY.exitUpstream;
 return <><PageHead title="本机出口共享" desc="允许 Server 将授权流量通过此设备访问 Internet 或指定网络。"/><Card title="出口能力" eyebrow="EXIT NODE" action={<Switch checked={config.exitEnabled!==false} onChange={v=>setv('exitEnabled',v)}/>}><Setting title="当前运行状态" desc="Agent 出口处理器"><Badge tone={status.exitRunning?'ok':'neutral'}>{status.exitRunning?'正在提供出口':'未运行'}</Badge></Setting><Setting title="允许访问 Internet" desc="允许作为公网出口"><Switch checked={!!config.allowInternet} onChange={v=>setv('allowInternet',v)}/></Setting><Setting title="允许访问私有网络" desc="访问 RFC1918 / 内网地址"><Switch checked={!!config.allowPrivateNetwork} onChange={v=>setv('allowPrivateNetwork',v)}/></Setting><Setting title="允许访问 Loopback" desc="高风险，默认应关闭"><Switch checked={!!config.allowLoopback} onChange={v=>setv('allowLoopback',v)}/></Setting></Card>
 <div className="cards-2"><Card title="上游代理" eyebrow="UPSTREAM"><div className="form-grid"><Field label="模式"><Select value={u.mode||''} onChange={e=>setv('exitUpstream.mode',e.target.value)}><option value="">直连</option><option value="socks5">SOCKS5</option><option value="http">HTTP</option></Select></Field><Field label="地址"><Input value={u.address||''} onChange={e=>setv('exitUpstream.address',e.target.value)} placeholder="127.0.0.1:1080"/></Field><Field label="用户名"><Input value={u.username||''} onChange={e=>setv('exitUpstream.username',e.target.value)}/></Field><Field label="密码"><Input type="password" value={u.password||''} onChange={e=>setv('exitUpstream.password',e.target.value)}/></Field></div></Card><Card title="出口访问控制" eyebrow="ACCESS POLICY"><Field label="策略模式"><Select value={config.accessMode||''} onChange={e=>setv('accessMode',e.target.value)}><option value="">关闭</option><option value="allow">仅允许列表</option><option value="deny">拒绝列表</option></Select></Field><Field label="域名规则"><Textarea rows="4" value={arr(config.accessDomains).join('\n')} onChange={e=>setv('accessDomains',split(e.target.value))}/></Field><Field label="CIDR / IP"><Textarea rows="4" value={arr(config.accessCidrs).join('\n')} onChange={e=>setv('accessCidrs',split(e.target.value))}/></Field></Card></div>
 <div className="actions end"><Button primary onClick={()=>save({exit:{enabled:config.exitEnabled,allowInternet:config.allowInternet,allowPrivateNetwork:config.allowPrivateNetwork,allowLoopback:config.allowLoopback,upstream:u,access:{mode:config.accessMode||'',domains:arr(config.accessDomains),cidrs:arr(config.accessCidrs)}}})}>保存出口共享设置</Button></div></>
}

function RuleEditor({value,exits,onChange}){
 const set=(k,v)=>onChange({...value,[k]:v});
 return <div className="form-grid"><Field label="规则名称"><Input value={value.name||''} onChange={e=>set('name',e.target.value)}/></Field><Field label="启用"><Select value={value.enabled?'on':'off'} onChange={e=>set('enabled',e.target.value==='on')}><option value="on">启用</option><option value="off">停用</option></Select></Field><Field label="动作"><Select value={value.action||'PROXY'} onChange={e=>set('action',e.target.value)}><option value="PROXY">PROXY</option><option value="DIRECT">DIRECT</option><option value="REJECT">REJECT</option></Select></Field><Field label="指定出口"><Select value={value.exit_id||''} disabled={value.action!=='PROXY'} onChange={e=>set('exit_id',e.target.value)}><option value="">跟随默认出口</option>{exits.map(x=><option key={x.deviceId||x.id} value={x.deviceId||x.id}>{x.name||x.deviceId}</option>)}</Select></Field><Field label="进程（每行一个）" className="full"><Textarea rows="3" value={arr(value.processes).join('\n')} onChange={e=>set('processes',split(e.target.value))}/></Field><Field label="域名 / IP / CIDR" className="full"><Textarea rows="3" value={arr(value.targets).join('\n')} onChange={e=>set('targets',split(e.target.value))}/></Field><Field label="端口"><Textarea rows="3" value={arr(value.ports).join('\n')} onChange={e=>set('ports',split(e.target.value))}/></Field><Field label="协议"><Textarea rows="3" value={arr(value.protocols).join('\n')} onChange={e=>set('protocols',split(e.target.value))}/></Field><label className="check-line"><input type="checkbox" checked={!!value.datagram_required} onChange={e=>set('datagram_required',e.target.checked)}/><span><strong>要求原生 UDP</strong><small>仅在支持 datagram 的路径上使用。</small></span></label><label className="check-line"><input type="checkbox" checked={!!value.handle_direct} disabled={value.action!=='DIRECT'} onChange={e=>set('handle_direct',e.target.checked)}/><span><strong>RelayProxy 托管 DIRECT</strong><small>由 RelayProxy 建立本地直连。</small></span></label></div>
}

function RoutingPage({config,exits,setv,save}){
 const r=config.routing||EMPTY.routing,[editing,setEditing]=useState(null),rules=arr(r.rules);
 const commit=x=>setv('routing.rules',x);
 const move=(i,d)=>{const n=[...rules],j=i+d;if(j<0||j>=n.length)return;[n[i],n[j]]=[n[j],n[i]];commit(n)};
 const edit=i=>setEditing({index:i,rule:JSON.parse(JSON.stringify(i>=0?rules[i]:{name:'新规则',enabled:true,action:'PROXY',exit_id:'',datagram_required:false,handle_direct:false,processes:[],targets:[],ports:[],protocols:['tcp','udp']}))});
 const saveEditor=()=>{const n=[...rules];if(editing.index<0)n.push(editing.rule);else n[editing.index]=editing.rule;commit(n);setEditing(null)};
 return <><PageHead title="分流规则" desc="按进程、域名/IP、端口和协议从上到下匹配，第一条命中的规则生效。" actions={<Button primary onClick={()=>edit(-1)}>＋ 新建规则</Button>}/><Card title="全局策略" eyebrow="ROUTING MODE"><div className="form-grid"><Field label="模式"><Select value={r.mode||'global_proxy'} onChange={e=>setv('routing.mode',e.target.value)}><option value="global_proxy">全局代理</option><option value="rule">规则模式</option><option value="direct">全局直连</option></Select></Field><Field label="规则未命中时"><Select value={r.default_action||'PROXY'} onChange={e=>setv('routing.default_action',e.target.value)}><option value="PROXY">PROXY</option><option value="DIRECT">DIRECT</option><option value="REJECT">REJECT</option></Select></Field></div></Card>
 <Card title="规则列表" eyebrow={rules.length+' RULES'}><div className="rule-table"><div className="rule-row rule-head"><span>#</span><span>规则</span><span>匹配条件</span><span>动作</span><span>操作</span></div>{rules.map((x,i)=><div className={cx('rule-row',!x.enabled&&'disabled')} key={(x.name||'rule')+'-'+i}><span className="drag">⋮⋮</span><div><div className="row"><strong>{x.name||'规则 '+(i+1)}</strong><Badge tone={x.enabled?'blue':'neutral'}>{x.enabled?'开启':'关闭'}</Badge></div><div className="mini">优先级 {i+1}</div></div><div className="chips">{arr(x.processes).slice(0,2).map(v=><span className="chip" key={'p'+v}>{v}</span>)}{arr(x.targets).slice(0,2).map(v=><span className="chip" key={'t'+v}>{v}</span>)}{arr(x.ports).slice(0,1).map(v=><span className="chip" key={'o'+v}>{v}</span>)}{!arr(x.processes).length&&!arr(x.targets).length&&!arr(x.ports).length&&<span className="mini">任意流量</span>}</div><div><Badge tone={x.action==='REJECT'?'danger':x.action==='DIRECT'?'blue':'ok'}>{x.action||'PROXY'}</Badge>{x.exit_id&&<div className="mini">{exitName(exits,x.exit_id)}</div>}</div><div className="rule-ops"><Button quiet disabled={i===0} onClick={()=>move(i,-1)}>↑</Button><Button quiet disabled={i===rules.length-1} onClick={()=>move(i,1)}>↓</Button><Button quiet onClick={()=>edit(i)}>编辑</Button><Button quiet danger onClick={()=>window.confirm('删除这条分流规则？')&&commit(rules.filter((_,n)=>n!==i))}>删除</Button></div></div>)}{!rules.length&&<div className="empty">尚无规则。切换到规则模式前请先添加规则。</div>}</div><div className="actions end top-gap"><Button primary onClick={()=>save({routing:r})}>保存分流规则</Button></div></Card>
 <Modal open={!!editing} title={editing&&editing.index>=0?'编辑分流规则':'新建分流规则'} wide onClose={()=>setEditing(null)} footer={<><Button onClick={()=>setEditing(null)}>取消</Button><Button primary onClick={saveEditor}>保存规则</Button></>}>{editing&&<RuleEditor value={editing.rule} exits={exits} onChange={rule=>setEditing({...editing,rule})}/>}</Modal></>
}

function RDPPage({status,targets,refreshTargets,refreshStatus,toast}){
 const[busy,setBusy]=useState('');
 const connect=async id=>{setBusy(id);try{const r=parseMutation(await call('goConnectRDP',id,true));if(!r.ok)throw new Error(r.message||'RDP 连接失败');toast('RDP 本地入口已建立');await refreshStatus()}catch(e){toast(e.message,'danger')}finally{setBusy('')}};
 const disconnect=async()=>{try{const r=parseMutation(await call('goDisconnectRDP'));if(!r.ok)throw new Error(r.message||'RDP 断开失败');await refreshStatus();toast('RDP 已断开')}catch(e){toast(e.message,'danger')}};
 return <><PageHead title="远程桌面" desc="仅显示 Server 授权的 RDP 目标，并优先建立 P2P TCP / UDP 辅助路径。" actions={<Button onClick={refreshTargets}>刷新设备</Button>}/>{status.rdpTargetId&&<Card title="当前 RDP 会话" eyebrow="ACTIVE SESSION"><div className="rdp-session"><div className="identity-icon">▣</div><div className="grow"><strong>{status.rdpTargetId}</strong><div className="mini">本地入口 {status.rdpListenAddr||'准备中'}</div></div><Badge tone="ok">已连接</Badge></div><div className="cards-3 compact top-gap"><div><div className="mini">TCP Path</div><strong>{status.rdpPathTcp||'Relay'}</strong></div><div><div className="mini">UDP Path</div><strong>{status.rdpPathUdp||(status.rdpUdpActive?'Active':'—')}</strong></div><div><div className="mini">UDP</div><strong>{status.rdpUdpActive?'Active':status.rdpUdpEnabled?'Ready':'Off'}</strong></div></div><div className="actions end top-gap"><Button danger onClick={disconnect}>断开会话</Button></div></Card>}<Card title="已授权设备" eyebrow={targets.length+' TARGETS'}><div className="target-list">{targets.map(x=>{const id=x.deviceId||x.id;return <div className="target-row" key={id}><div className="identity-icon small">▣</div><div className="grow"><strong>{x.name||id}</strong><div className="mono mini">{id}</div></div><Badge tone={x.online?'ok':'neutral'}>{x.online?'在线':'离线'}</Badge><Button primary disabled={!x.online||!!busy} onClick={()=>connect(id)}>{busy===id?'连接中…':'连接'}</Button></div>})}{!targets.length&&<div className="empty">暂无已授权 RDP 设备。</div>}</div></Card></>
}

function MessagesPage({messages,refresh,clear,toast}){
 const[filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const classified=m=>({code:!!m.verificationCode||m.messageType==='verification_code'||m.popupType==='verification_code',important:m.messageType==='important'||m.popupType==='important'});
 const q=query.trim().toLowerCase();
 const filtered=messages.filter(m=>{const type=classified(m),typeOK=filter==='all'||(filter==='code'&&type.code)||(filter==='important'&&type.important)||(filter==='normal'&&!type.code&&!type.important);if(!typeOK)return false;if(!q)return true;return [m.title,m.content,m.source,m.verificationCode,m.messageType,m.popupType].some(v=>String(v||'').toLowerCase().includes(q))});
 const copy=async t=>{if(!t)return;if(hasBridge('goCopyClipboard'))await call('goCopyClipboard',String(t));else await navigator.clipboard.writeText(String(t));toast('已复制')};
 return <><PageHead title="消息" desc="接收 Server 按身份隔离下发的通知、验证码与重要消息。" actions={<><Button onClick={refresh}>刷新</Button><Button danger onClick={clear}>清空</Button></>}/>
 <div className="filter-bar"><div className="segment">{[['all','全部'],['code','验证码'],['normal','普通消息'],['important','重要提醒']].map(x=><button className={filter===x[0]?'active':''} key={x[0]} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div><div className="message-search"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索标题、内容、来源或验证码"/><span className="mini">{filtered.length} 条</span></div></div>
 <div className="message-list">{filtered.slice().reverse().map((m,i)=>{const type=classified(m),code=type.code,important=type.important;return <article className={cx('message-card',important&&'important')} key={m.id||i}><div className={cx('message-icon',code?'code':important?'important':'')}>{code?'#':important?'!':'✦'}</div><div className="grow"><div className="row between"><strong>{m.title||(code?'验证码':important?'重要消息':'消息')}</strong><Badge tone={code?'ok':important?'danger':'blue'}>{code?'验证码':important?'重要':'通知'}</Badge></div><div className="mini">{(m.source||'RelayProxy')+' · '+fmtTime(m.createdAt)}</div><p>{m.content||''}</p>{m.verificationCode&&<button className="code-box" onClick={()=>copy(m.verificationCode)}>{m.verificationCode}<small>点击复制</small></button>}</div></article>})}{!filtered.length&&<Card><div className="empty">{messages.length?'没有符合当前筛选条件的消息。':'暂无消息。'}</div></Card>}</div></>
}

function MonitorPage({connections,refresh,clear,openNative}){
 const active=connections.filter(x=>/active|connecting/i.test(x.state||x.status||'')).length,total=connections.reduce((s,x)=>s+Number(x.bytes_up||x.bytesUp||0)+Number(x.bytes_down||x.bytesDown||0),0);
 return <><PageHead title="实时监控" desc="观察当前连接、进程、目标、路径与流量。" actions={<><Button onClick={refresh}>刷新</Button><Button onClick={openNative}>独立窗口</Button><Button danger onClick={clear}>清理历史</Button></>}/><div className="cards-3"><Metric label="连接总数" value={connections.length} hint="当前缓存"/><Metric label="活跃连接" value={active} hint="active / connecting"/><Metric label="累计流量" value={fmtBytes(total)} hint="当前监控窗口"/></div><Card title="连接列表" eyebrow="LIVE CONNECTIONS"><div className="conn-table"><div className="conn-row conn-head"><span>应用 / 目标</span><span>路径</span><span>状态</span><span>流量</span><span>开始时间</span></div>{connections.slice().sort((a,b)=>Date.parse(b.started_at||b.startedAt||0)-Date.parse(a.started_at||a.startedAt||0)).map((x,i)=>{const state=x.state||x.status||'—',proc=x.process||x.process_name||x.app||x.application||'未知进程',target=x.target||x.host||x.remote||x.destination||x.address||'—',path=x.path||x.route||x.transport||x.action||'—',up=x.bytes_up??x.bytesUp??x.upload??0,down=x.bytes_down??x.bytesDown??x.download??0;return <div className="conn-row" key={x.id||i}><div><strong>{proc}</strong><div className="mono mini">{target}</div></div><span>{path}</span><Badge tone={tone(state)}>{state}</Badge><span className="mono">{fmtBytes(up)+' ↑ · '+fmtBytes(down)+' ↓'}</span><span className="mini">{fmtTime(x.started_at||x.startedAt)}</span></div>})}{!connections.length&&<div className="empty">暂无连接记录。</div>}</div></Card></>
}

function DiagnosticsPage({diagnostics,logs,refreshDiagnostics,clearLogs,copyLogs}){
 const[filter,setFilter]=useState('all');
 const match=(line,type)=>{if(type==='all')return true;const s=String(line||'');if(type==='relay')return /relay|tunnel|control stream|server|handshake|tls/i.test(s);if(type==='p2p')return /p2p|punch|candidate|rendezvous|stun|hole.?punch/i.test(s);if(type==='proxy')return /proxy|socks5?|http proxy|divert|windivert|routing|fakeip/i.test(s);if(type==='exit')return /exit|egress|upstream|public direct|direct path|acl/i.test(s);return true};
 const visible=logs.filter(line=>match(line,filter));
 return <><PageHead title="诊断与日志" desc="检查网络接管、隧道、Direct/P2P 状态，并查看 Agent 实时日志。" actions={<><Button onClick={refreshDiagnostics}>刷新诊断</Button><Button onClick={copyLogs}>复制日志</Button><Button danger onClick={clearLogs}>清空日志</Button></>}/>
 <div className="cards-2"><Card title="运行诊断" eyebrow="DIAGNOSTICS"><pre className="diagnostic-json">{JSON.stringify(diagnostics||{},null,2)}</pre></Card><Card title="建议检查" eyebrow="HEALTH"><div className="stack"><div className="notice">透明代理未启动时，请检查管理员权限、网络服务与 WinDivert 驱动状态。</div><div className="notice">QUIC 性能异常时可对比 Direct / P2P / Relay 路径并运行出口测速。</div><div className="notice warn">保存标记为“需重启”的配置后，使用设置页重启客户端。</div></div></Card></div>
 <Card title="运行日志" eyebrow={visible.length+' / '+logs.length+' LINES'}><div className="log-toolbar"><div className="segment">{[['all','全部'],['relay','中继'],['p2p','P2P'],['proxy','代理'],['exit','出口']].map(x=><button key={x[0]} className={filter===x[0]?'active':''} onClick={()=>setFilter(x[0])}>{x[1]}</button>)}</div><span className="mini">{filter==='all'?'显示全部日志':'仅显示匹配分类的日志'}</span></div><div className="log-console">{visible.length?visible.map((x,i)=><div key={i} className={cx(/error|failed|失败|fatal|timeout/i.test(x)&&'log-error',/warn|retry|警告/i.test(x)&&'log-warn')}>{x}</div>):<div className="muted">当前分类暂无日志</div>}</div></Card></>
}

function SettingsPage({config,setv,save,toast,onReload,onRestart,onQuit}){
 const[service,setService]=useState(null),[preview,setPreview]=useState('');
 useEffect(()=>{if(hasBridge('goGetNetworkServiceStatus'))callJSON('goGetNetworkServiceStatus',{}).then(setService).catch(()=>{})},[]);
 const act=async(name,msg)=>{try{const r=parseMutation(await call(name));if(!r.ok&&r.message)throw new Error(r.message);toast(msg);if(hasBridge('goGetNetworkServiceStatus'))setService(await callJSON('goGetNetworkServiceStatus',{}))}catch(e){toast(e.message,'danger')}};
 const auto=async v=>{try{const r=parseMutation(await call('goSetAutostart',v));if(!r.ok&&r.message)throw new Error(r.message);setv('isAutostart',v,false);toast(v?'已启用开机自启':'已关闭开机自启')}catch(e){toast(e.message,'danger')}};
 const previews={
  uac:{title:'Windows 服务 / UAC',body:<div className="notice warn">安装或修复 RelayProxy Network Service 需要 Windows 管理员权限。日常 GUI、代理和托盘运行不需要管理员身份。</div>},
  unsaved:{title:'未保存修改',body:<div className="notice warn">连接、代理或分流规则存在未保存草稿。离开、重载、重启或退出前会要求确认。</div>},
  restart:{title:'需要重启',body:<div className="notice">监听地址、端口或部分启动参数已保存，但必须重启 RelayProxy 才能完全生效。</div>},
  pending:{title:'设备等待审批',body:<div className="notice warn">当前安装已向 Relay Server 发起接入请求。请使用对应身份登录 Server 并审批需要的能力。</div>},
  rejected:{title:'设备授权不可用',body:<div className="notice danger">服务端已拒绝此安装身份，或管理员撤销了当前设备授权。代理、出口与 RDP 能力将停止。</div>},
  exitdown:{title:'已选出口不可用',body:<div className="notice warn">保存的出口已离线、删除或撤销授权。RelayProxy 不会静默切换其他出口或 DIRECT。</div>},
  verification:{title:'验证码弹窗',body:<PopupPreview type="verification"/>},
  message:{title:'普通消息弹窗',body:<PopupPreview type="message"/>},
  important:{title:'重要提醒弹窗',body:<PopupPreview type="important"/>}
 };
 const current=previews[preview];
 return <><PageHead title="设置" desc="主题、托盘行为、开机自启与 Windows 网络服务维护。"/>
 {config.restartRequired&&<div className="notice warn">以下设置需要重启客户端后生效：{arr(config.restartFields).join('、')||'启动参数'}。</div>}
 {config.reloadPending&&<div className="notice warn">配置文件中的策略与当前运行状态不同，可重新读取并应用。</div>}
 <div className="cards-2"><Card title="外观与窗口" eyebrow="APPEARANCE"><Setting title="主题" desc="支持跟随 Windows 系统设置"><Select value={config.theme||'system'} onChange={e=>setv('theme',e.target.value)}><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></Select></Setting><Setting title="关闭时最小化到托盘" desc="关闭主窗口后 Agent 保持运行"><Switch checked={!!config.minimizeToTray} onChange={v=>setv('minimizeToTray',v)}/></Setting><Field label="消息弹窗自动关闭（秒）"><Input type="number" min="0" max="3600" value={config.verificationPopupTimeoutSec??12} onChange={e=>setv('verificationPopupTimeoutSec',Number(e.target.value))}/></Field><div className="actions end top-gap"><Button primary onClick={()=>save({gui:{theme:config.theme,minimizeToTray:config.minimizeToTray,verificationPopupTimeoutSec:Number(config.verificationPopupTimeoutSec)}})}>保存界面设置</Button></div></Card>
 <Card title="启动与文件" eyebrow="APPLICATION"><Setting title="开机自启" desc="透明代理模式会使用管理员登录任务"><Switch checked={!!config.isAutostart} onChange={auto}/></Setting><Setting title="配置文件" desc={config.configPath||'未指定'}><Button onClick={()=>call('goOpenConfigDir')}>打开目录</Button></Setting><Setting title="版本" desc="RelayProxy Agent"><span className="mono">{config.version||'dev'}</span></Setting><div className="actions top-gap"><Button onClick={onReload}>重新读取并应用</Button><Button onClick={onRestart}>重启客户端</Button><Button danger onClick={onQuit}>退出</Button></div></Card></div>
 <Card title="Windows 网络服务" eyebrow="NETWORK SERVICE"><div className="setting"><div className="grow"><b>服务状态</b><div className="mini">{service?.message||'透明代理由低权限 GUI 与 SYSTEM 网络服务协作完成。'}</div></div><Badge tone={service?.ready?'ok':service?.installed?'warn':'neutral'}>{service?.ready?'就绪':service?.running?'运行中':service?.installed?'已安装':'未安装'}</Badge></div>{service&&<div className="service-grid"><div><span>安装</span><b>{service.installed?'是':'否'}</b></div><div><span>运行</span><b>{service.running?'是':'否'}</b></div><div><span>自动启动</span><b>{service.autoStartKnown?(service.autoStart?'是':'否'):'未知'}</b></div><div><span>版本匹配</span><b>{service.versionMatch?'是':'否'}</b></div><div><span>恢复策略</span><b>{service.recoveryKnown?(service.recoveryEnabled?'已启用':'未启用'):'未知'}</b></div><div><span>PID</span><b className="mono">{service.pid||'—'}</b></div>{service.binaryPath&&<div className="service-path"><span>程序路径</span><b className="mono">{service.binaryPath}</b></div>}</div>}<div className="actions top-gap"><Button onClick={()=>act('goRepairNetworkService','网络服务修复完成')}>修复服务</Button><Button danger onClick={()=>window.confirm('卸载 RelayProxy Windows 网络服务？')&&act('goUninstallNetworkService','网络服务已卸载')}>卸载服务</Button></div></Card>
 <Card title="交互状态 / 弹窗预览" eyebrow="STATE GALLERY"><div className="gallery-grid">{[['uac','Windows 服务 / UAC','安装透明代理服务'],['unsaved','未保存修改','离开 / 重载 / 重启保护'],['restart','需要重启','启动参数变更'],['pending','设备待审批','Identity 设备审批状态'],['rejected','设备拒绝 / 撤销','授权失效状态'],['exitdown','出口不可用','不静默改选出口'],['verification','验证码弹窗','复制 / 自动关闭'],['message','普通消息','内容型弹窗'],['important','重要提醒','高优先级提醒']].map(x=><button key={x[0]} className="gallery-item" onClick={()=>setPreview(x[0])}><b>{x[1]}</b><span>{x[2]}</span></button>)}</div></Card>
 <Modal open={!!current} title={current?.title||''} onClose={()=>setPreview('')} footer={<Button primary onClick={()=>setPreview('')}>关闭预览</Button>}>{current?.body}</Modal></>
}

function PopupPreview({type}){
 const isCode=type==='verification',important=type==='important';
 return <div className={cx('popup-preview',important&&'important')}><div className="popup-preview-head"><div className={cx('message-icon',isCode?'code':important?'important':'')}>{isCode?'#':important?'!':'✦'}</div><div><div className="eyebrow">{important?'IMPORTANT':isCode?'VERIFICATION CODE':'MESSAGE'}</div><strong>{important?'重要提醒':isCode?'收到新的验证码':'收到新消息'}</strong></div></div><div className="mini top-gap">来自 RelayProxy · 刚刚</div>{isCode&&<div className="preview-code">482913</div>}<p>{important?'Tokyo 出口已从 Public Direct 降级至 Relay，请检查公网直连状态。':isCode?'用于登录验证，请勿向他人泄露。':'设备审批已完成，新的授权能力已同步到本机。'}</p><div className="actions end"><Button>{isCode?'稍后处理':'知道了'}</Button>{isCode&&<Button primary>复制验证码</Button>}</div></div>
}

function SpeedModal({open,exits,initialExit,onClose,toast}){
 const[exitID,setExitID]=useState(''),[duration,setDuration]=useState(3),[busy,setBusy]=useState(false),[result,setResult]=useState(null);
 useEffect(()=>{if(open){setExitID(initialExit||'');setResult(null)}},[open,initialExit]);
 const run=async()=>{setBusy(true);setResult(null);try{const p=parseMutation(await call('goRunSpeedTest',exitID,Number(duration)));if(!p.ok)throw new Error(p.message||'测速失败');setResult(p.result||p);toast('出口测速完成')}catch(e){setResult({error:e.message})}finally{setBusy(false)}};
 const leg=(label,v={})=><div><div className="eyebrow">{label}</div><div className="big small-big">{Number(v.megabitsPerSecond??v.mbps??0).toFixed(2)} Mbps</div><div className="mini">{(v.path||'—')+' · '+fmtBytes(v.bytesPerSecond||0,true)}</div>{v.quic&&<div className="mini">丢包 {Number(v.quic.sent_packet_loss_pct||0).toFixed(2)}% · RTT 抖动 {Number(v.quic.rtt_deviation_ms||0).toFixed(1)} ms · GSO {v.quic.gso?'ON':'OFF'}</div>}</div>;
 return <Modal open={open} title="出口双向测速" onClose={onClose} footer={<><Button onClick={onClose}>关闭</Button><Button primary disabled={busy} onClick={run}>{busy?'测速中…':'开始测速'}</Button></>}><div className="form-grid"><Field label="出口"><Select value={exitID} onChange={e=>setExitID(e.target.value)}><option value="">当前 / 自动出口</option>{exits.map(x=><option key={x.deviceId||x.id} value={x.deviceId||x.id}>{x.name||x.deviceId}</option>)}</Select></Field><Field label="每方向时长（秒）"><Input type="number" min="1" max="30" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></Field></div>{result&&<div className={cx('speed-result',result.error&&'error')}>{result.error?result.error:<>{leg('上行',result.upload||result.up)}{leg('下行',result.download||result.down)}</>}</div>}</Modal>
}

export default function App(){
 const[page,setPage]=useState(()=>sessionStorage.getItem('relayproxy-react-page')||'overview'),[status,setStatus]=useState({connected:false,proxyExits:[]}),[config,setConfig]=useState(EMPTY),[loaded,setLoaded]=useState(false),[dirty,setDirty]=useState(false),[pendingAction,setPendingAction]=useState(null),[exits,setExits]=useState([]),[exitsReady,setExitsReady]=useState(false),[targets,setTargets]=useState([]),[messages,setMessages]=useState([]),[connections,setConnections]=useState([]),[logs,setLogs]=useState([]),[diagnostics,setDiagnostics]=useState({}),[toastState,setToastState]=useState(null),[speedOpen,setSpeedOpen]=useState(false),[speedExit,setSpeedExit]=useState('');
 const toastTimer=useRef(null);
 const toast=useCallback((message,t='normal')=>{clearTimeout(toastTimer.current);setToastState({message,t});toastTimer.current=setTimeout(()=>setToastState(null),3200)},[]);
 const theme=useCallback(mode=>{const m=['light','dark','system'].includes(mode)?mode:'system',dark=m==='dark'||(m==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.themeMode=m;document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.classList.toggle('dark',dark)},[]);
 const refreshStatus=useCallback(async()=>{if(!hasBridge('goGetStatus'))return null;try{const x=await callJSON('goGetStatus',{});setStatus(x||{});if(Array.isArray(x?.proxyExits)){setExits(x.proxyExits);setExitsReady(true)}return x}catch{return null}},[]);
 const refreshConfig=useCallback(async()=>{if(!hasBridge('goGetConfig'))return false;try{const x=await callJSON('goGetConfig',null);if(!x||x.configError)throw new Error(x?.configError||'配置读取失败');setConfig({...EMPTY,...x,socks5:{...EMPTY.socks5,...x.socks5},http:{...EMPTY.http,...x.http},p2p:{...EMPTY.p2p,...x.p2p},exitUpstream:{...EMPTY.exitUpstream,...x.exitUpstream},network:{...EMPTY.network,...x.network},routing:{...EMPTY.routing,...x.routing,rules:arr(x.routing?.rules)}});theme(x.theme||'system');setLoaded(true);setDirty(false);return true}catch(e){toast(e.message,'danger');return false}},[theme,toast]);
 const refreshExits=useCallback(async()=>{if(hasBridge('goGetProxyExits'))try{setExits(arr(await callJSON('goGetProxyExits',[])));setExitsReady(true)}catch(e){toast('读取授权出口失败：'+e.message,'danger')}},[toast]);
 const refreshTargets=useCallback(async()=>{if(hasBridge('goGetRDPTargets'))try{setTargets(arr(await callJSON('goGetRDPTargets',[])))}catch(e){toast(e.message,'danger')}},[toast]);
 const refreshMessages=useCallback(async()=>{if(hasBridge('goGetMessages'))try{setMessages(arr(await callJSON('goGetMessages',[])))}catch{}},[]);
 const refreshConnections=useCallback(async()=>{if(hasBridge('goGetConnections'))try{setConnections(arr(await callJSON('goGetConnections',[])))}catch{}},[]);
 const refreshLogs=useCallback(async()=>{if(hasBridge('goGetLogs'))try{setLogs(arr(await callJSON('goGetLogs',[])).map(logText).filter(Boolean))}catch{}},[]);
 const refreshDiagnostics=useCallback(async()=>{if(hasBridge('goGetDiagnostics'))try{setDiagnostics(await callJSON('goGetDiagnostics',{}))}catch(e){toast(e.message,'danger')}},[toast]);

 useEffect(()=>{let disposed=false;(async()=>{await refreshConfig();if(!disposed)await Promise.all([refreshStatus(),refreshExits(),refreshTargets(),refreshMessages(),refreshConnections(),refreshLogs(),refreshDiagnostics()])})();const a=setInterval(refreshStatus,1500),b=setInterval(()=>{refreshConnections();refreshMessages();refreshLogs()},2500);const mq=matchMedia('(prefers-color-scheme: dark)'),mh=()=>document.documentElement.dataset.themeMode==='system'&&theme('system');mq.addEventListener?.('change',mh);const uninstall=installNativeHooks({onStatus:x=>{if(typeof x==='string')try{x=JSON.parse(x)}catch{return}setStatus(x||{});if(Array.isArray(x?.proxyExits)){setExits(x.proxyExits);setExitsReady(true)}},onLog:x=>setLogs(p=>[...p.slice(-1999),logText(x)].filter(Boolean)),onMessage:m=>setMessages(p=>{if(!m?.id)return[...p,m].filter(Boolean).slice(-500);const i=p.findIndex(x=>x.id===m.id);if(i<0)return[...p,m].slice(-500);const n=[...p];n[i]=m;return n}),onTheme:m=>{theme(m);setConfig(p=>({...p,theme:m}))},onAutostart:v=>setConfig(p=>({...p,isAutostart:!!v}))});return()=>{disposed=true;clearInterval(a);clearInterval(b);clearTimeout(toastTimer.current);mq.removeEventListener?.('change',mh);uninstall()}},[refreshConfig,refreshStatus,refreshExits,refreshTargets,refreshMessages,refreshConnections,refreshLogs,refreshDiagnostics,theme]);

 useEffect(()=>{sessionStorage.setItem('relayproxy-react-page',page);if(page==='rdp')refreshTargets();if(page==='messages')refreshMessages();if(page==='monitor')refreshConnections();if(page==='diagnostics'){refreshDiagnostics();refreshLogs()}},[page,refreshTargets,refreshMessages,refreshConnections,refreshDiagnostics,refreshLogs]);
 useEffect(()=>theme(config.theme||'system'),[config.theme,theme]);

 const setv=useCallback((path,value,markDirty=true)=>{setConfig(prev=>{const next=structuredClone(prev),keys=path.split('.');let o=next;for(let i=0;i<keys.length-1;i++){o[keys[i]]=o[keys[i]]&&typeof o[keys[i]]==='object'?o[keys[i]]:{};o=o[keys[i]]}o[keys[keys.length-1]]=value;return next});if(markDirty)setDirty(true)},[]);
 const save=useCallback(async payload=>{if(!loaded||!config.revision){toast('配置尚未就绪，暂不能保存','danger');return false}try{const r=await saveConfig(config.revision,payload);if(!r.ok)throw new Error(r.message||'保存失败');await refreshConfig();await refreshStatus();toast(r.restartRequired?(r.message||'已保存，部分设置需重启'):(r.message||'已保存'));return true}catch(e){toast(e.message,'danger');return false}},[loaded,config.revision,toast,refreshConfig,refreshStatus]);
 const select=useCallback(async id=>{try{const r=parseMutation(await call('goSelectExit',id));if(!r.ok&&r.message)throw new Error(r.message);await refreshConfig();await refreshStatus();toast(id?'已切换到 '+exitName(exits,id):'已切换为自动选择')}catch(e){toast(e.message,'danger')}},[exits,refreshStatus,toast]);
 const clearMessages=useCallback(async()=>{if(messages.length&&!confirm('清空本设备的消息历史？'))return;await call('goClearMessages');setMessages([]);toast('消息历史已清空')},[messages.length,toast]);
 const clearConnections=useCallback(async()=>{await call('goClearConnections');await refreshConnections();toast('已清理结束连接历史')},[refreshConnections,toast]);
 const clearLogs=useCallback(async()=>{await call('goClearLogs');setLogs([]);toast('日志已清空')},[toast]);
 const copyLogs=useCallback(async()=>{const text=logs.join('\n');if(hasBridge('goCopyClipboard'))await call('goCopyClipboard',text);else await navigator.clipboard.writeText(text);toast('日志已复制')},[logs,toast]);
 const requestPage=useCallback(next=>{if(next===page)return;if(dirty){setPendingAction({kind:'page',target:next});return}setPage(next)},[dirty,page]);
 const requestLifecycle=useCallback(kind=>{if(dirty){setPendingAction({kind});return}if(kind==='reload')call('goReloadConfig').then(async()=>{await refreshConfig();await refreshStatus();toast('已重新读取配置')}).catch(e=>toast(e.message,'danger'));else if(kind==='restart')call('goRestart');else if(kind==='quit'&&window.confirm('退出 RelayProxy？'))call('goQuit')},[dirty,refreshConfig,refreshStatus,toast]);
 const discardAndContinue=useCallback(async()=>{const action=pendingAction;if(!action)return;setPendingAction(null);setDirty(false);if(action.kind==='page'){await refreshConfig();setPage(action.target);return}if(action.kind==='reload'){try{await call('goReloadConfig');await refreshConfig();await refreshStatus();toast('已重新读取配置')}catch(e){toast(e.message,'danger')}return}if(action.kind==='restart'){await call('goRestart');return}if(action.kind==='quit'){await call('goQuit')}},[pendingAction,refreshConfig,refreshStatus,toast]);
 useEffect(()=>{const h=e=>{if(!dirty)return;e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',h);return()=>window.removeEventListener('beforeunload',h)},[dirty]);
 const selectedExit=status.selectedExit||config.defaultExitId||'';
 const selectedExitItem=selectedExit?exits.find(x=>(x.deviceId||x.id)===selectedExit):null;
 const exitUnavailable=!!(exitsReady&&selectedExit&&(!selectedExitItem||selectedExitItem.online===false));
 const approval=String(status.approvalState||'').toLowerCase();
 const approvalPending=/pending|wait|approval|待审批/.test(approval);
 const approvalRejected=/reject|denied|revoked|撤销|拒绝/.test(approval);
 const cycleTheme=useCallback(async()=>{if(dirty){toast('当前有未保存修改，请先保存或放弃后再切换主题','danger');return}const next=config.theme==='dark'?'light':config.theme==='light'?'system':'dark';try{const r=parseMutation(await call('goSetTheme',next));if(!r.ok&&r.message)throw new Error(r.message);await refreshConfig();toast(next==='dark'?'已切换深色主题':next==='light'?'已切换浅色主题':'已切换为跟随系统')}catch(e){toast(e.message,'danger')}},[config.theme,dirty,refreshConfig,toast]);
 const title=useMemo(()=>{for(const g of NAV){const x=g.items.find(i=>i[0]===page);if(x)return x[2]}return page==='settings'?'设置':'RelayProxy'},[page]);
 const p={status,config,exits,setv,save,toast};
 let content;
 if(page==='overview')content=<Overview {...p} onSelect={select} onRefresh={refreshStatus} onGoto={requestPage}/>;
 else if(page==='devices')content=<Devices {...p}/>;
 else if(page==='connection')content=<Connection {...p}/>;
 else if(page==='exits')content=<Exits status={status} exits={exits} selected={status.selectedExit||config.defaultExitId||''} onSelect={select} onSpeed={id=>{setSpeedExit(id||'');setSpeedOpen(true)}}/>;
 else if(page==='proxy')content=<ProxyPage {...p}/>;
 else if(page==='exitshare')content=<ExitShare {...p}/>;
 else if(page==='routing')content=<RoutingPage {...p}/>;
 else if(page==='rdp')content=<RDPPage status={status} targets={targets} refreshTargets={refreshTargets} refreshStatus={refreshStatus} toast={toast}/>;
 else if(page==='messages')content=<MessagesPage messages={messages} refresh={refreshMessages} clear={clearMessages} toast={toast}/>;
 else if(page==='monitor')content=<MonitorPage connections={connections} refresh={refreshConnections} clear={clearConnections} openNative={()=>call('goOpenConnections')}/>;
 else if(page==='diagnostics')content=<DiagnosticsPage diagnostics={diagnostics} logs={logs} refreshDiagnostics={refreshDiagnostics} clearLogs={clearLogs} copyLogs={copyLogs}/>;
 else content=<SettingsPage config={config} setv={setv} save={save} toast={toast} onReload={()=>requestLifecycle('reload')} onRestart={()=>requestLifecycle('restart')} onQuit={()=>requestLifecycle('quit')}/>;
 return <div className="app-shell"><aside className="sidebar"><div className="side-brand"><Logo/><div><strong>RelayProxy</strong><span>Agent</span></div></div><div className="nav-scroll">{NAV.map(g=><div className="nav-group" key={g.group}><div className="group-name">{g.group}</div>{g.items.map(x=><button key={x[0]} className={cx('nav-item',page===x[0]&&'active')} onClick={()=>requestPage(x[0])}><span className="nav-icon">{x[1]}</span><span>{x[2]}</span>{x[0]==='messages'&&messages.length>0&&<i className="nav-dot"/>}</button>)}</div>)}</div><div className="sidebar-footer"><button className={cx('nav-item',page==='settings'&&'active')} onClick={()=>requestPage('settings')}><span className="nav-icon">⚙</span><span>设置</span></button><div className="connection-mini"><span className={cx('dot',status.connected?'online':'offline')}/><div><strong>{status.connected?'已连接':'未连接'}</strong><span>{status.latency||0} ms</span></div></div></div></aside><section className="workspace"><header className="topbar"><div className="crumb"><b>{title}</b><span>·</span><span>{status.deviceName||config.deviceName||'本设备'}</span></div><div className="top-actions">{dirty&&<Badge tone="blue">未保存</Badge>}{config.restartRequired&&<Badge tone="warn">需重启</Badge>}<button className="icon-btn" title="主题" onClick={cycleTheme}>◐</button><button className="icon-btn" title="最小化" onClick={()=>call('goMinimizeWindow')}>—</button></div></header><main className="main">{approvalPending&&<div className="notice warn state-banner"><b>设备等待审批。</b> 请在 Relay Server 使用当前身份审批此设备所需能力。</div>}{approvalRejected&&<div className="notice danger state-banner"><b>设备授权不可用。</b> 当前设备可能已被拒绝或撤销，代理、出口与 RDP 能力会受限。</div>}{exitUnavailable&&<div className="notice warn state-banner"><b>已选出口不可用。</b> RelayProxy 不会静默改选其他出口；请在“出口选择”重新选择。 <Button quiet onClick={()=>requestPage('exits')}>重新选择</Button></div>}{content}</main></section><SpeedModal open={speedOpen} exits={exits} initialExit={speedExit} onClose={()=>setSpeedOpen(false)} toast={toast}/><Modal open={!!pendingAction} title="有未保存的修改" onClose={()=>setPendingAction(null)} footer={<><Button onClick={()=>setPendingAction(null)}>继续编辑</Button><Button danger onClick={discardAndContinue}>放弃修改并继续</Button></>}><div className="notice warn">当前页面存在尚未保存的配置草稿。离开、重载、重启或退出会丢失这些修改。</div></Modal>{toastState&&<div className={cx('toast show',toastState.t==='danger'&&'danger')}>{toastState.message}</div>}</div>
}
