import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {DeviceLabel} from './DeviceLabel.js';
import {Icon} from './icons.jsx';
import {api,json,list,fmtDate,fmtBytes,localDate,isoDate,normalizedCapabilities,permissionDefs,validChannelId,validatePortRange,pushURL} from './api.js';
import {groups,getGroup,normalizeForSave,configEqual} from './settings.js';
import {summarizeSession,summarizePathReport} from './diagnostics.js';

const pages={overview:'运行总览',devices:'设备管理',identities:'身份管理',exits:'出口节点',sessions:'活跃会话',p2p:'P2P 直连',messages:'消息历史',channels:'推送渠道',rdp:'RDP 公网入口',audit:'RDP 连接审计',security:'RDP 安全策略',settings:'服务配置'};
const nav=[['概览',[['overview','运行总览']]],['设备与身份',[['devices','设备管理'],['identities','身份管理'],['exits','出口节点']]],['连接',[['sessions','实时连接'],['p2p','P2P 路径'],['rdp','RDP 公网入口'],['audit','连接审计'],['security','IP 安全策略']]],['消息',[['messages','消息历史'],['channels','推送渠道']]],['系统',[['settings','服务配置']]]];
const navIcons={overview:'dashboard',devices:'devices',identities:'users',exits:'globe',sessions:'activity',p2p:'route',rdp:'monitor',audit:'terminal',security:'shield',messages:'bell',channels:'share',settings:'settings'};
function BrandMark({login=false}){return <div className={'brand '+(login?'login-brand':'')}><span className="brand-icon brand-image"><img src="/img/logo.png" alt="" loading="eager"/></span><div className="brand-wordmark"><strong>RelayProxy</strong><small>{login?'SECURE ADMIN ACCESS':'SERVER CONSOLE'}</small></div></div>}
const adminPages=new Set(['identities','rdp','audit','security','settings']);
const blank={dashboard:{},devices:[],enrollments:[],identities:[],exits:[],sessions:[],p2p:[],channels:[],messages:[],pushInfo:null,ingress:[],bans:[],rules:[],systemGrants:[],settings:null};
const queryFromHash=()=>{const [p,t]=location.hash.slice(1).split('/');return {page:pages[p]?p:'overview',settingTab:getGroup(t||'admin').id};};
function Banner({children,type=''}) {return <div className={'config-help '+type}>{children}</div>}
function Badge({children,tone=''}){return <span className={'badge '+tone}>{children}</span>}
function Action({children,onClick,tone='',disabled=false,type='button'}){const invoke=e=>{try{const result=onClick?.(e);if(result&&typeof result.catch==='function')result.catch(err=>console.error('操作失败',err));}catch(err){console.error('操作失败',err)}};return <button type={type} disabled={disabled} className={'btn sm '+tone} onClick={onClick?invoke:undefined}>{children}</button>}
function Field({label,value,onChange,type='text',placeholder='',options=[],disabled=false,wide=false,help='',required=false}){
 return <label className={'field '+(wide?'wide':'')}><span>{label}</span>{type==='lines'?<textarea value={Array.isArray(value)?value.join('\n'):value??''} disabled={disabled} rows={4} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/>:type==='select'||type==='bool-select'?<select value={String(value??'')} disabled={disabled} onChange={e=>onChange(type==='bool-select'?e.target.value==='true':e.target.value)}>{(type==='bool-select'?[['false','HTTP'],['true','HTTPS']]:options).map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>:type==='checkbox'?<span className="toggle-field"><span>{value?'已启用':'已关闭'}</span><input type="checkbox" disabled={disabled} checked={!!value} onChange={e=>onChange(e.target.checked)}/></span>:<input type={type} min={type==='number'?0:undefined} required={required} disabled={disabled} placeholder={placeholder} value={value??''} onChange={e=>onChange(type==='number'?(e.target.value===''?'':Number(e.target.value)):e.target.value)}/>} {help&&<small>{help}</small>}</label>;
}
function Select({value,onChange,items=[],placeholder='请选择',disabled=false}){return <select className="input" disabled={disabled} value={value||''} onChange={e=>onChange(e.target.value)}><option value="">{placeholder}</option>{items.map(x=><option key={x.id} value={x.id}>{x.name||x.deviceName||x.id}</option>)}</select>}
function Table({columns,items,render,empty='暂无数据'}){return <div className="table-wrap"><table><thead><tr>{columns.map((col,i)=><th key={i}>{col}</th>)}</tr></thead><tbody>{items.length?items.map((item,i)=><tr key={item.id||item.sourceIp||i}>{render(item,i)}</tr>):<tr><td colSpan={columns.length}><div className="empty-state">{empty}</div></td></tr>}</tbody></table></div>}
function Head({title,desc,actions}){return <div className="page-head"><div><h1>{title}</h1>{desc&&<p>{desc}</p>}</div>{actions&&<div className="actions">{actions}</div>}</div>}
function Panel({title,desc,actions,children,className=''}){return <section className={'card page-section '+className}><div className="card-title-area"><div><h2>{title}</h2>{desc&&<p className="section-description">{desc}</p>}</div>{actions}</div>{children}</section>}
function Caps({value,onChange,allowed=permissionDefs.map(p=>p[0])}){return <div className="form-grid">{permissionDefs.filter(([key])=>allowed.includes(key)).map(([key,name])=><label className="toggle-field" key={key}><span>{name}</span><input type="checkbox" checked={value.includes(key)} onChange={e=>{let next=e.target.checked?[...value,key]:value.filter(x=>x!==key);if(key==='rdp.host'&&!e.target.checked)next=next.filter(x=>x!=='rdp.public');onChange(normalizedCapabilities(next));}}/></label>)}</div>}
function Dialog({dialog,close}){const ref=useRef(null);useEffect(()=>{if(!dialog)return;const onKey=e=>{if(e.key==='Escape')close()};document.addEventListener('keydown',onKey);return()=>document.removeEventListener('keydown',onKey)},[dialog,close]);if(!dialog)return null;return <div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={ref} role="dialog" aria-modal="true" aria-label={dialog.title} className={'dialog-window '+(dialog.wide?'wide':'')}><header className="dialog-header"><h2>{dialog.title}</h2><Action onClick={close}>✕</Action></header><div className="modal-content-scroll">{dialog.body}</div><footer className="dialog-footer"><Action onClick={close}>关闭</Action></footer></section></div>}
function Login({onLogin,error}){const [username,setUser]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[localError,setLocalError]=useState('');return <div className="login-screen"><div className="login-card"><BrandMark login/><h1>管理控制台</h1><p className="muted">登录以管理设备、出口和服务配置</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setLocalError('');try{await onLogin(username,password)}catch(err){setLocalError(err.message)}finally{setBusy(false)}}}><Field label="用户名" value={username} onChange={setUser} required/><Field label="密码" value={password} onChange={setPassword} type="password" required/>{(localError||error)&&<p className="err-notice">{localError||error}</p>}<Action tone="primary" type="submit" disabled={busy}>{busy?'正在登录…':'登录'}</Action></form></div></div>}
export function App(){
 const [user,setUser]=useState(null),[authReady,setAuthReady]=useState(false),[authError,setAuthError]=useState('');
 const [route,setRoute]=useState(queryFromHash),[theme,setTheme]=useState(()=>localStorage.getItem('relayproxy-theme')||'system');
 const [data,setData]=useState(blank),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [dialog,setDialog]=useState(null),[messageChannel,setMessageChannel]=useState('');
 const [draft,setDraft]=useState(null),[saved,setSaved]=useState(null),[settingsTab,setSettingsTab]=useState(route.settingTab),[saving,setSaving]=useState(false);
 const [refreshCounter,setRefreshCounter]=useState(0);const settingsRef=useRef({saved,draft});settingsRef.current={saved,draft};
 const admin=user?.role==='admin';const dirty=!!saved?.config&&!!draft&&!configEqual(draft,saved.config);
 const flash=useCallback(message=>{setNotice(message);setTimeout(()=>setNotice(''),3500)},[]);
 const go=useCallback((page,tab)=>{if(dirty&&page!==route.page&&!window.confirm('配置尚未保存，确定切换页面？修改会保留到返回设置时。'))return;location.hash=page==='settings'?'settings/'+(tab||settingsTab):page},[dirty,route.page,settingsTab]);
 const refresh=useCallback(async (asUser=user,silent=false)=>{
  if(!asUser)return; if(!silent)setLoading(true);setError('');
  const jobs={dashboard:'/dashboard',devices:'/devices',enrollments:'/enrollments?state=pending',identities:asUser.role==='admin'?'/identities':'/identity-options',exits:'/exits',sessions:'/sessions/active',p2p:'/p2p/sessions',channels:'/message-channels',messages:'/messages?limit=500',pushInfo:'/message-push-info',...(asUser.role==='admin'?{ingress:'/rdp/ingress',bans:'/rdp/security/bans',rules:'/rdp/security/rules',systemGrants:'/system-identity-grants?resourceId=server',settings:'/server/config'}:{})};
  const outcomes=await Promise.allSettled(Object.entries(jobs).map(async ([key,url])=>[key,await api(url)]));
  const delta={};const errors=[];
  for(const o of outcomes){if(o.status==='fulfilled'){const [key,result]=o.value;delta[key]=['dashboard','settings','pushInfo'].includes(key)?result:list(result)}else errors.push(o.reason)}
  if(errors.some(x=>x.status===401)){setUser(null);setLoading(false);setSaved(null);setDraft(null);setAuthError('登录已过期，请重新登录');return}
  setData(prev=>({...prev,...delta}));
  if(delta.settings){
   const current=settingsRef.current;
   const hasEdits=!!current.saved?.config&&!!current.draft&&!configEqual(current.draft,current.saved.config);
   if(hasEdits){
    if(current.saved.revision!==delta.settings.revision)errors.push(new Error('Server 配置已在其他会话更新。当前编辑已保留，保存前请备份并重新读取最新配置。'));
   }else{
    setSaved(delta.settings);
    setDraft(delta.settings.config);
   }
  }
  if(errors.length)setError('部分数据无法读取：'+[...new Set(errors.map(x=>x.message))].join('；'));
  setLoading(false);
 },[user]);
 useEffect(()=>{let cancelled=false;api('/auth/me').then(u=>{if(cancelled)return;const principal=u.user||u;setUser(principal)}).catch(e=>{if(!cancelled&&e.status!==401)setAuthError(e.message)}).finally(()=>{if(!cancelled)setAuthReady(true)});return()=>{cancelled=true}},[]);
 useEffect(()=>{if(user)refresh(user);},[user,refreshCounter]);
 useEffect(()=>{const update=()=>{const next=queryFromHash();setRoute(next);setSettingsTab(next.settingTab)};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[]);
 useEffect(()=>{const dark=theme==='dark'||theme==='system'&&window.matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('relayproxy-theme',theme);const mq=window.matchMedia('(prefers-color-scheme: dark)');const fn=()=>{if(theme==='system')document.documentElement.dataset.theme=mq.matches?'dark':'light'};mq.addEventListener('change',fn);return()=>mq.removeEventListener('change',fn)},[theme]);
 useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn)},[dirty]);
 const run=useCallback(async(fn,success)=>{try{setError('');const result=await fn();if(success)flash(success);setRefreshCounter(x=>x+1);return result}catch(e){setError(e.message);throw e}},[flash]);
 const close=useCallback(()=>setDialog(null),[]);
 const ctx={user,admin,data,run,refresh:()=>setRefreshCounter(x=>x+1),flash,go,open:(title,body,wide=false)=>setDialog({title,body,wide}),close,setError,messageChannel,setMessageChannel,draft,setDraft,saved,setSaved,saving,setSaving,settingsTab,setSettingsTab};
 if(!authReady)return <div className="login-screen">正在检查登录状态…</div>;
 if(!user)return <Login error={authError} onLogin={async (username,password)=>{await api('/auth/login',json('POST',{username,password}));const result=await api('/auth/me');setUser(result.user||result);setAuthError('')}}/>;
 let page=route.page;if(!admin&&adminPages.has(page))page='overview';
 return <div id="app"><aside className="sidebar"><BrandMark/><div className="nav-scroll">{nav.map(([title,items])=><section className="nav-group" key={title}><div className="group-name">{title}</div>{items.filter(([p])=>admin||!adminPages.has(p)).map(([p,label])=><button type="button" key={p} onClick={()=>go(p)} className={'nav-item '+(page===p?'active':'')}><span className="nav-icon"><Icon name={navIcons[p]} size={17}/></span><span>{label}</span>{p==='devices'&&data.enrollments.length>0&&<span className="nav-count">{data.enrollments.length}</span>}</button>)}</section>)}</div><div className="sidebar-footer"><div className="side-status"><i className="status-dot"/><div><strong>Server · {error?'DEGRADED':'ONLINE'}</strong><small>Relay 控制台</small></div></div><button className="user-chip" onClick={()=>setDialog({title:'账户管理',body:<Account user={user} onPasswordChanged={()=>{setDialog(null);setUser(null);setData(blank);setDraft(null);setSaved(null);setAuthError('密码已修改，请重新登录')}} logout={async()=>{try{await api('/auth/logout',{method:'POST'})}finally{setDialog(null);setUser(null);setData(blank);setDraft(null);setSaved(null)}}}/>})}><span className="avatar">{user.username?.slice(0,1).toUpperCase()||'A'}</span><span className="grow"><strong>{user.username}</strong><small>{admin?'全局管理员':'身份管理员'}</small></span></button></div></aside><div className="workspace"><header className="topbar"><div className="crumb"><span>RelayProxy</span><span style={{opacity:.5}}>/</span><b>{pages[page]}</b></div><div className="topbar-right"><div className="theme-seg">{[['system','自动'],['light','浅色'],['dark','深色']].map(([v,t])=><button key={v} onClick={()=>setTheme(v)} className={theme===v?'active':''}>{t}</button>)}</div><Action disabled={loading} onClick={()=>ctx.refresh()}>{loading?'刷新中':'刷新'}</Action><a className="btn sm" href="/classic" title="使用原有管理台（完整旧版功能）">经典版</a></div></header><main className="main-scroll"><div className="main-inner">{error&&<div className="err-notice" role="alert">{error}</div>}{data.settings?.restartRequired&&<Banner type="warn"><b>配置已保存，等待服务重启。</b> {list(data.settings.restartFields).join('、')}</Banner>}{page==='overview'?<Overview ctx={ctx}/>:page==='devices'?<Devices ctx={ctx}/>:page==='identities'?<Identities ctx={ctx}/>:page==='exits'?<Exits ctx={ctx}/>:page==='sessions'||page==='p2p'?<Connections ctx={ctx} p2pOnly={page==='p2p'}/>:page==='messages'?<Messages ctx={ctx}/>:page==='channels'?<Channels ctx={ctx}/>:page==='rdp'?<Ingress ctx={ctx}/>:page==='audit'?<Audit ctx={ctx}/>:page==='security'?<Security ctx={ctx}/>:<Settings ctx={ctx}/>}</div></main></div><Dialog dialog={dialog} close={close}/>{notice&&<div className="toast-live" role="status">{notice}</div>}</div>;
}
function Account({user,onPasswordChanged,logout}){
 const [old,setOld]=useState(''),[pw,setPw]=useState(''),[confirmPw,setConfirmPw]=useState('');
 const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const submit=async e=>{
  e.preventDefault();setError('');
  if(pw.length<8||pw.length>128||!pw.trim()){setError('新密码需要 8–128 个字符且不能为空白');return}
  if(pw!==confirmPw){setError('两次密码不一致');return}
  setBusy(true);
  try{await api('/auth/password',json('PUT',{currentPassword:old,newPassword:pw}));onPasswordChanged()}
  catch(e){setError(e.message)}finally{setBusy(false)}
 };
 return <form onSubmit={submit}><p className="dialog-note">当前账户：{user.username}。修改密码后所有管理会话必须重新登录。</p><div className="form-grid"><Field label="原密码" type="password" value={old} onChange={setOld} required/><Field label="新密码" type="password" value={pw} onChange={setPw} required/><Field label="确认新密码" type="password" value={confirmPw} onChange={setConfirmPw} required/></div>{error&&<p className="err-notice" role="alert">{error}</p>}<div className="form-actions"><Action tone="primary" disabled={busy} type="submit">{busy?'正在修改…':'修改密码'}</Action><Action disabled={busy} onClick={()=>logout().catch(e=>setError(e.message))}>退出登录</Action></div></form>
}
function Overview({ctx}){
 const {data,go,admin}=ctx;
 const d=data.dashboard||{};
 const online=Number(d.onlineDevices??data.devices.filter(x=>x.status==='online').length);
 const total=data.devices.length;
 const exits=Number(d.onlineExits??data.exits.length);
 const sessions=Number(d.activeConnections??data.sessions.length);
 const p2p=Number(d.activeP2PSessions??data.p2p.length);
 const waiting=data.enrollments.length;
 const up=Math.max(0,Number(d.todayUpload)||0),down=Math.max(0,Number(d.todayDownload)||0);
 const totalTraffic=up+down;
 const ratio=totalTraffic>0?Math.round(up/totalTraffic*100):50;
 const metrics=[
  {label:'在线设备',value:online,hint:'已登记 '+total+' 台',icon:'devices',tone:'blue',page:'devices'},
  {label:'可用出口',value:exits,hint:'在线的代理出口',icon:'globe',tone:'teal',page:'exits'},
  {label:'活跃连接',value:sessions,hint:'当前活跃流',icon:'activity',tone:'violet',page:'sessions'},
  {label:'P2P 会话',value:p2p,hint:'当前协商 / 直连',icon:'route',tone:'amber',page:'p2p'}
 ];
 return <>
  <Head title="中继网络一览" desc="设备、传输路径、安全审批与实时流量，尽在一处。" actions={<Action tone="primary" onClick={()=>go('devices')}>查看设备 →</Action>}/>
  <section className="overview-hero" aria-label="RelayProxy 网络拓扑">
   <div className="overview-hero-copy">
    <span className="overview-hero-kicker"><span className="overview-online-dot"/> RELAYPROXY NETWORK</span>
    <h2>连接每一台设备，<span>让流量自由流动。</span></h2>
    <p>通过 Relay、QUIC 与 P2P 组织你的私有网络。所有设备与出口均由服务端身份和能力授权控制。</p>
    <div className="overview-hero-meta"><span><Icon name="shield" size={15}/> 身份隔离与授权</span><span><Icon name="activity" size={15}/> 实时状态监测</span></div>
   </div>
   <div className="network-visual" role="img" aria-label="客户端经过 Relay Server 连接出口节点的网络拓扑示意图">
    <svg viewBox="0 0 460 235" preserveAspectRatio="xMidYMid meet" aria-hidden="true">
      <defs><linearGradient id="rpLine" x1="0" x2="1"><stop stopColor="#81e6f9"/><stop offset="1" stopColor="#c4b5fd"/></linearGradient><radialGradient id="rpAura"><stop stopColor="#fff" stopOpacity=".36"/><stop offset="1" stopColor="#fff" stopOpacity="0"/></radialGradient></defs>
      <circle cx="230" cy="117" r="100" fill="url(#rpAura)"/>
      <g stroke="url(#rpLine)" strokeWidth="2" strokeDasharray="6 7" opacity=".78" fill="none"><path d="M85 76 Q151 31 230 115"/><path d="M85 166 Q160 196 230 115"/><path d="M230 115 Q310 37 384 76"/><path d="M230 115 Q312 194 384 166"/></g>
      <g fill="#fff" opacity=".94"><circle cx="140" cy="64" r="4"/><circle cx="149" cy="174" r="4"/><circle cx="323" cy="63" r="4"/><circle cx="319" cy="175" r="4"/></g>
      <g fill="#122450" stroke="#9ad9ff" strokeWidth="1.5"><rect x="35" y="46" width="100" height="63" rx="14"/><rect x="35" y="139" width="100" height="63" rx="14"/><rect x="326" y="46" width="100" height="63" rx="14"/><rect x="326" y="139" width="100" height="63" rx="14"/></g>
      <g fill="#fff" fontSize="12" fontWeight="600" textAnchor="middle"><text x="85" y="70">Client</text><text x="85" y="89" fill="#9bdcf4" fontSize="10">Agent</text><text x="85" y="162">Client</text><text x="85" y="181" fill="#9bdcf4" fontSize="10">Agent</text><text x="376" y="70">Exit</text><text x="376" y="89" fill="#9bdcf4" fontSize="10">Node</text><text x="376" y="162">Exit</text><text x="376" y="181" fill="#9bdcf4" fontSize="10">Node</text></g>
      <circle cx="230" cy="115" r="61" fill="#fff" opacity=".13"/><circle cx="230" cy="115" r="47" fill="#fff" stroke="#dcecff" strokeWidth="2"/><circle cx="230" cy="115" r="33" fill="#dceaff"/><g textAnchor="middle"><text x="230" y="113" fill="#1d4ed8" fontSize="12" fontWeight="800">RELAY</text><text x="230" y="127" fill="#5774a8" fontSize="9">SERVER</text></g>
    </svg>
    <div className="network-caption">逻辑拓扑示意 · 实际路径由网络能力决定</div>
   </div>
  </section>
  <div className="grid g4 overview-metrics">{metrics.map(m=><button type="button" className={'card overview-metric metric-'+m.tone} onClick={()=>go(m.page)} key={m.label}><span className="metric-icon"><Icon name={m.icon} size={21}/></span><span className="overview-metric-copy"><span className="metric-label">{m.label}</span><strong className="metric-value">{m.value}</strong><span className="metric-hint">{m.hint}</span></span><span className="metric-arrow">↗</span></button>)}</div>
  <div className="grid two-one page-section">
   <Panel title="Relay 节点状态" actions={<Badge tone="ok">管理台在线</Badge>}>
    <div className="overview-status-grid">
      <div><span>管理地址</span><strong className="mono">{location.origin}</strong></div>
      <div><span>今日上传</span><strong>{fmtBytes(up)}</strong></div>
      <div><span>今日下载</span><strong>{fmtBytes(down)}</strong></div>
      <div><span>待审批设备</span><strong>{waiting} 台</strong></div>
    </div>
   </Panel>
   <Panel title="快捷入口" desc="常用操作，一键直达">
    <div className="overview-shortcuts">
      {[[ 'devices','devices','设备审批',waiting?'待处理 '+waiting+' 台':'设备与能力授权'],['sessions','activity','查看连接','查看实时路径和 QUIC 统计'],['channels','bell','消息渠道','推送规则与通知管理'],...(admin?[['settings','settings','服务配置','隧道、P2P、出口和 ACL']]:[])].map(([p,icon,label,note])=><button type="button" className="overview-shortcut" onClick={()=>go(p)} key={p}><span className="shortcut-icon"><Icon name={icon} size={17}/></span><span><b>{label}</b><small>{note}</small></span><span className="shortcut-arrow">↗</span></button>)}
    </div>
   </Panel>
  </div>
  <div className="grid g2 overview-insights">
   <Panel title="今日传输流量" desc="基于 Server 实际统计的上传与下载">
     <div className="traffic-total">{fmtBytes(totalTraffic)}</div>
     <div className="traffic-track" aria-label="上传和下载流量比例"><span style={{width:totalTraffic>0?ratio+'%':'50%'}}/><span/></div>
     <div className="traffic-legend"><span><i className="traffic-up"/> 上行 {fmtBytes(up)}</span><span><i className="traffic-down"/> 下行 {fmtBytes(down)}</span></div>
   </Panel>
   <Panel title="设备与连接" desc="运行状态与待处理事项">
     <div className="overview-health"><div><span className="health-label">在线设备占比</span><strong>{total?Math.round(online/total*100):0}%</strong><span className="health-progress"><i style={{width:(total?Math.min(100,online/total*100):0)+'%'}}/></span></div><div className="health-divider"/><div><span className="health-label">待审批申请</span><strong>{waiting}</strong><small>前往设备管理处理</small></div></div>
   </Panel>
  </div>
  <Panel title="最近设备" desc="最近接入或活跃的已登记设备" actions={<Action onClick={()=>go('devices')}>查看全部 →</Action>}><Table columns={['设备','系统 / 角色','状态','最近在线']} items={data.devices.slice().sort((a,b)=>(Date.parse(b.lastSeenAt)||0)-(Date.parse(a.lastSeenAt)||0)).slice(0,6)} render={device=><><td><DeviceLabel name={device.name} id={device.id}/></td><td>{device.platform||'—'} · {device.deviceMode||'—'}</td><td><Badge tone={device.status==='online'?'ok':''}>{device.status==='online'?'在线':'离线'}</Badge></td><td>{fmtDate(device.lastSeenAt)}</td></>}/></Panel>
 </>
}
function Devices({ctx}){
 const {data,run,open,close,admin}=ctx;const [q,setQ]=useState(''),[status,setStatus]=useState(''),[role,setRole]=useState('');
 const filtered=data.devices.filter(d=>[d.name,d.id,d.identityName,d.identityId].join(' ').toLowerCase().includes(q.toLowerCase())&&(!role||d.deviceMode===role)&&(!status||(status==='disabled'?d.approvalState==='revoked':d.approvalState==='approved'&&d.status===status)));
 const approve=entry=>open('审批 · '+(entry.deviceName||entry.id),<Approval entry={entry} run={run} close={close}/>);
 const manage=d=>open('设备 · '+d.name,<DeviceDetails key={d.id} device={d} ctx={ctx}/> ,true);
 return <><Head title="设备管理" desc="设备审批、身份归属与授权能力统一管理。" actions={<Action onClick={()=>ctx.refresh()}>刷新设备</Action>}/><Panel title={'待审批设备 · '+data.enrollments.length} desc="新设备通过身份 ID 发起连接申请，批准的能力不能超过其声明范围。"><Table columns={['设备','系统','申请能力','最近申请','操作']} items={data.enrollments} render={e=><><td><DeviceLabel name={e.deviceName} id={e.fingerprint?'指纹 '+e.fingerprint.slice(0,24)+'…':e.id}/></td><td>{e.platform} {e.arch}</td><td>{list(e.requestedCapabilities).join('、')}</td><td>{fmtDate(e.lastSeenAt)}</td><td><div className="table-action"><Action tone="primary" onClick={()=>approve(e)}>审批</Action><Action onClick={()=>{if(confirm('拒绝该设备申请？'))run(()=>api('/enrollments/'+encodeURIComponent(e.id)+'/reject',json('POST',{})),'申请已拒绝')}}>拒绝</Action></div></td></>} empty="当前没有待审批设备"/></Panel><Panel title="已登记设备" actions={<span className="muted">{filtered.length} / {data.devices.length}</span>}><div className="device-filters"><input className="input" aria-label="搜索设备名称、ID 或身份" placeholder="设备名称 / ID / 身份" value={q} onChange={e=>setQ(e.target.value)}/><select className="input" aria-label="按设备状态筛选" value={status} onChange={e=>setStatus(e.target.value)}><option value="">所有状态</option><option value="online">在线</option><option value="offline">离线</option><option value="disabled">已撤销</option></select><select className="input" aria-label="按设备角色筛选" value={role} onChange={e=>setRole(e.target.value)}><option value="">所有角色</option><option value="CLIENT">客户端</option><option value="EXIT">出口节点</option><option value="BOTH">两种角色</option></select></div><Table columns={['设备','身份归属','角色 / 系统','状态','传输','最近在线','操作']} items={filtered} render={d=><><td><DeviceLabel name={d.name} id={d.id}/></td><td>{d.identityName||d.identityId||'未分配'}</td><td>{d.deviceMode}<small>{d.platform} / {d.arch}</small></td><td><Badge tone={d.status==='online'?'ok':''}>{d.approvalState==='revoked'?'已撤销':d.status==='online'?'在线':'离线'}</Badge></td><td>{d.transport||'—'}</td><td>{fmtDate(d.lastSeenAt)}</td><td><div className="table-action"><Action onClick={()=>manage(d)}>管理</Action>{admin&&<Action onClick={()=>open('更改身份归属',<IdentityMove device={d} ctx={ctx}/>) }>归属</Action>}</div></td></>}/></Panel></>;
}
function Approval({entry,run,close}){const [caps,setCaps]=useState(list(entry.requestedCapabilities));return <><p className="dialog-note">仅可批准设备当前申请的能力；RDP 公网入口必须同时具有 RDP 主机能力。</p><Caps value={caps} allowed={list(entry.requestedCapabilities)} onChange={setCaps}/><div className="form-actions"><Action onClick={close}>取消</Action><Action tone="primary" disabled={!caps.length} onClick={async()=>{if(!confirm('批准选中的能力？'))return;await run(()=>api('/enrollments/'+encodeURIComponent(entry.id)+'/approve',json('POST',{capabilities:caps})),'审批成功');close()}}>批准选中能力</Action></div></>}
function IdentityMove({device,ctx}){const [id,setId]=useState(device.identityId||'');return <><p className="dialog-note">改变设备归属将断开当前连接，并清除以此设备为目标的跨身份授权。</p><Field label="所属身份" type="select" options={ctx.data.identities.map(x=>[x.id,x.name])} value={id} onChange={setId}/><div className="form-actions"><Action tone="primary" disabled={!id} onClick={async()=>{if(!confirm('确定调整设备所属身份？'))return;await ctx.run(()=>api('/devices/'+encodeURIComponent(device.id)+'/identity',json('PUT',{identityId:id})),'身份归属已更新');ctx.close()}}>保存归属</Action></div></>}
function DeviceDetails({device,ctx}){
 const {data,run,close,admin}=ctx;const [caps,setCaps]=useState(list(device.approvedCapabilities));const [tab,setTab]=useState('capabilities');
 const [grants,setGrants]=useState([]),[target,setTarget]=useState(''),[grant,setGrant]=useState(null),[features,setFeatures]=useState([]),[expires,setExpires]=useState('');
 const [legacy,setLegacy]=useState([]),[legacyCandidates,setLegacyCandidates]=useState(null);
 const loadGrants=useCallback(()=>api('/device-identity-grants?targetDeviceId='+encodeURIComponent(device.id)).then(x=>setGrants(list(x))),[device.id]);
 useEffect(()=>{loadGrants().catch(()=>{})},[loadGrants]);
 const openLegacy=async()=>{setTab('legacy');try{const result=await api('/rdp/targets?controllerId='+encodeURIComponent(device.id));setLegacy(list(result?.targets).map(x=>x.deviceId));setLegacyCandidates(data.devices.filter(x=>x.id!==device.id&&(x.approvedCapabilities||[]).includes('rdp.host')))}catch(e){ctx.setError(e.message)}};
 const methods=[['capabilities','授权能力'],['grants','跨身份授权'],['legacy','历史 RDP 关系']].filter(([key])=>key!=='legacy'||(admin&&!device.identityId&&list(device.approvedCapabilities).includes('rdp.controller')));
 return <><div className="detail-list"><div>设备 ID　<span className="mono">{device.id}</span></div><div>身份归属　{device.identityName||device.identityId||'未分配'}</div><div>平台　{device.platform} / {device.arch}</div><div>状态　{device.status} · {device.approvalState}</div></div><div className="tab-line">{methods.map(([key,title])=><Action key={key} tone={tab===key?'active':''} onClick={()=>key==='legacy'?openLegacy():setTab(key)}>{title}</Action>)}</div>{tab==='capabilities'&&<><Banner>修改能力后设备会断开并重新认证；全部停用请使用撤销设备授权。</Banner><Caps value={caps} onChange={setCaps}/><div className="form-actions"><Action tone="primary" disabled={!caps.length} onClick={async()=>{if(!confirm('保存授权并使设备重新连接？'))return;await run(()=>api('/devices/'+encodeURIComponent(device.id)+'/capabilities',json('PUT',{capabilities:caps})),'设备授权已保存');close()}}>保存授权</Action></div></>}
 {tab==='grants'&&<><Banner>同身份设备访问自动允许；跨身份访问需要授权功能及有效期。</Banner><div className="form-grid"><Field label="被授权身份" value={target} onChange={setTarget} type="select" options={data.identities.filter(x=>x.id!==device.identityId).map(x=>[x.id,x.name])}/><Field label="过期时间" type="datetime-local" value={expires} onChange={setExpires}/></div><div className="form-grid">{[['proxy.use','代理出口'],['rdp.connect','RDP 连接']].filter(([k])=>k==='proxy.use'?list(device.approvedCapabilities).includes('proxy.exit'):list(device.approvedCapabilities).includes('rdp.host')).map(([k,label])=><label key={k} className="toggle-field">{label}<input type="checkbox" checked={features.includes(k)} onChange={e=>setFeatures(old=>e.target.checked?[...old,k]:old.filter(v=>v!==k))}/></label>)}</div><div className="form-actions"><Action tone="primary" onClick={async()=>{if(!target||!features.length){ctx.setError('请选择被授权身份及授权功能');return;}const body={granteeIdentityId:target,features,expiresAt:isoDate(expires)};await run(()=>grant?api('/device-identity-grants/'+grant.id,json('PATCH',{...body,revision:grant.revision,...(!expires?{clearExpiresAt:true}:{})})):api('/device-identity-grants',json('POST',{...body,targetDeviceId:device.id})),'跨身份授权已保存');await loadGrants();setGrant(null);setFeatures([])}}>{grant?'保存授权':'新建授权'}</Action></div><Table columns={['被授权身份','能力','到期','操作']} items={grants} render={g=><><td>{g.granteeIdentityName||g.granteeIdentityId}</td><td>{list(g.features).join('、')}</td><td>{g.expiresAt?fmtDate(g.expiresAt):'永久'}</td><td><div className="table-action"><Action onClick={()=>{setGrant(g);setTarget(g.granteeIdentityId);setFeatures(list(g.features));setExpires(localDate(g.expiresAt))}}>编辑</Action><Action tone="danger" onClick={async()=>{if(confirm('删除此跨身份授权？')){await run(()=>api('/device-identity-grants/'+g.id+'?revision='+g.revision,{method:'DELETE'}));loadGrants()}}}>删除</Action></div></td></>}/></>}
 {tab==='legacy'&&<><p className="dialog-note">历史 RDP 关系仅保留用于迁移，不再授权生产连接；生产授权请使用跨身份授权。</p><div className="form-grid">{list(legacyCandidates).map(d=><label className="toggle-field" key={d.id}><DeviceLabel name={d.name} id={d.id}/><input type="checkbox" checked={legacy.includes(d.id)} onChange={e=>setLegacy(old=>e.target.checked?[...old,d.id]:old.filter(x=>x!==d.id))}/></label>)}</div><div className="form-actions"><Action tone="primary" onClick={async()=>{await run(()=>api('/devices/'+device.id+'/rdp-targets',json('PUT',{targetDeviceIds:legacy})),'历史 RDP 关系已保存')}}>保存历史关系</Action></div></>}
 <hr/ ><div className="form-actions"><Action tone="danger" onClick={async()=>{if(confirm('撤销设备授权并立即断开连接？')){await run(()=>api('/devices/'+device.id+'/revoke',json('POST',{})),'授权已撤销');close()}}}>撤销授权</Action>{admin&&<Action tone="danger" onClick={async()=>{if(confirm('永久删除设备及所有历史授权？')){await run(()=>api('/devices/'+device.id,{method:'DELETE'}),'设备已删除');close()}}}>删除设备</Action>}</div></>;
}
function Identities({ctx}){const {data,run,open,close}=ctx;return <>
 <Head title="身份与登录" desc="身份隔离设备、消息与资源访问；账号和连接 ID 独立管理。" actions={<Action tone="primary" onClick={()=>open('创建身份',<IdentityCreate ctx={ctx}/>)}>＋ 创建身份</Action>}/>
 <Panel title={'身份列表 · '+data.identities.length}><Table columns={['身份','登录账号','状态','策略版本','最近更新','操作']} items={data.identities} render={d=><><td><DeviceLabel name={d.name} id={d.shortId||d.id}/></td><td>{d.loginUsername||'—'}</td><td><Badge tone={d.status==='active'?'ok':''}>{d.status==='active'?'启用':'禁用'}</Badge></td><td>{d.policyRevision}</td><td>{fmtDate(d.updatedAt)}</td><td><Action onClick={()=>open('编辑身份',<IdentityEditor identity={d} run={run} close={close}/>)}>管理</Action></td></>}/></Panel></>}
function IdentityCreate({ctx}){const [name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setError('');if(password.length<8){setError('初始密码至少 8 个字符');return}setBusy(true);try{await ctx.run(()=>api('/identities',json('POST',{name:name.trim(),username:username.trim(),password})),'身份已创建');ctx.close()}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <form className="create-dialog-form" onSubmit={submit}><p className="dialog-note">新身份会生成独立连接 ID，首次创建时需设置登录凭据。</p><div className="form-grid"><Field label="身份名称" value={name} onChange={setName} required/><Field label="登录用户名" value={username} onChange={setUsername} required/><Field label="初始密码（8–128 位）" type="password" value={password} onChange={setPassword} required/></div>{error&&<p className="err-notice" role="alert">{error}</p>}<div className="form-actions"><Action disabled={busy} onClick={ctx.close}>取消</Action><Action tone="primary" type="submit" disabled={busy}>{busy?'创建中…':'确认创建身份'}</Action></div></form>}

function IdentityEditor({identity,run,close}){const [name,setName]=useState(identity.name),[status,setStatus]=useState(identity.status||'active'),[login,setLogin]=useState(identity.loginUsername||''),[password,setPassword]=useState('');return <><div className="form-grid"><Field label="身份名称" value={name} onChange={setName}/><Field label="状态" value={status} onChange={setStatus} type="select" options={ [['active','启用'],['disabled','禁用']] }/></div><div className="form-actions"><Action tone="primary" onClick={async()=>{await run(()=>api('/identities/'+identity.id,json('PATCH',{name,status,policyRevision:identity.policyRevision})),'身份已更新');close()}}>保存身份</Action></div><hr/><h3>独立登录</h3><p className="dialog-note">修改账户信息会注销对应身份的管理会话。</p><div className="form-grid"><Field label="登录用户名" value={login} onChange={setLogin}/><Field label="新密码" type="password" value={password} onChange={setPassword}/></div><div className="form-actions"><Action tone="primary" disabled={!password||password.length<8} onClick={async()=>{await run(()=>api('/identities/'+identity.id+'/password',json('PUT',{username:login.trim().toLowerCase(),password})),'登录账户已更新');close()}}>更新登录与密码</Action></div></>}
function Exits({ctx}){return <><Head title="出口节点" desc="已批准的代理出口和 Server 本机出口；使用范围由服务端 ACL 与身份授权共同限制。"/><div className="exit-grid">{ctx.data.exits.map(e=><div className="exit-card" key={e.deviceId}><div className="card-title-area"><DeviceLabel name={e.deviceName} id={e.deviceId}/><Badge tone="ok">在线</Badge></div><div className="detail-list"><div>传输　{e.transport||'—'}</div><div>活跃流　{e.activeStreams??0}</div><div>Public Direct　{e.publicDirect?.available?'已验证':'不可用'}</div></div>{list(e.publicDirect?.endpoints).map((x,i)=><p className="dialog-note mono" key={i}>{x.address} · {x.state}</p>)}<div className="form-actions"><Action onClick={()=>navigator.clipboard.writeText(e.deviceId)}>复制出口 ID</Action></div></div>)}{!ctx.data.exits.length&&<div className="card empty-state">暂无在线出口节点</div>}</div></>}
function Connections({ctx,p2pOnly}){
 const {data}=ctx;
 const [capture,setCapture]=useState(-1),[captureError,setCaptureError]=useState('');
 const mounted=useRef(true),collecting=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const capture30=async()=>{
  if(collecting.current)return;
  collecting.current=true;setCapture(0);setCaptureError('');
  const startedAt=new Date().toISOString(), samples=[];
  try{
   for(let i=0;i<=30;i++){
    if(!mounted.current)return;
    samples.push({collectedAt:new Date().toISOString(),sessions:await api('/sessions/active')});
    if(mounted.current)setCapture(i);
    if(i<30)await new Promise(resolve=>setTimeout(resolve,1000));
   }
   if(!mounted.current)return;
   const report={schemaVersion:1,startedAt,finishedAt:new Date().toISOString(),durationSeconds:30,samples};
   const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));
   const anchor=document.createElement('a');anchor.href=url;
   anchor.download='relay-diagnostics-'+startedAt.replace(/[-:]/g,'').replace(/\..*/, '').replace('T','-')+'.json';
   document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
   ctx.flash('三端诊断采集完成，报告已下载');
  }catch(err){if(mounted.current){setCaptureError(err.message);ctx.setError(err.message)}}
  finally{collecting.current=false;if(mounted.current)setCapture(-1)}
 };
 const reportView=raw=>{const r=summarizePathReport(raw);return <><b>{r.name}</b>{r.reason&&<small>{r.reason}</small>}{r.detail&&<small>{r.detail}</small>}</>};
 return <><Head title={p2pOnly?'P2P / Direct 路径':'实时连接'} desc="查看 Server 与设备的 QUIC 统计、当前直连路径、回退和租约信息。" actions={<div className="actions"><Action onClick={ctx.refresh}>刷新状态</Action>{!p2pOnly&&<Action disabled={capture>=0} onClick={capture30}>{capture>=0?`采集中 ${capture}/30 秒`:'采集 30 秒诊断'}</Action>}</div>}/>
 {capture>=0&&<Banner>正在采集三端诊断：{capture} / 30 秒。请保持问题流量持续传输。</Banner>}{captureError&&<p className="err-notice">诊断采集失败：{captureError}</p>}
 {!p2pOnly&&<Panel title="活跃会话" desc="每个设备会话的传输数据及路径诊断。"><Table columns={['设备','角色','当前出口','传输','活跃流','上传 / 下载','三端诊断']} items={data.sessions} render={session=>{const s=summarizeSession(session,data.devices);return <><td><DeviceLabel name={s.client} id={s.clientId}/></td><td>{s.role}</td><td><DeviceLabel name={s.exit} id={session.exitDeviceId}/></td><td>{s.transport}</td><td>{s.streams}</td><td>{fmtBytes(s.bytesUp)} / {fmtBytes(s.bytesDown)}</td><td className="diagnostic-cell">{s.relayRttMs!==undefined?<><b>Relay RTT {s.relayRttMs} ms · 丢包 {s.relayLost??0}</b><small>设备 Relay RTT {s.remoteRelayRttMs??'—'} ms · 丢包 {s.remoteRelayLost??'—'}</small></>:<small>暂无 QUIC 统计</small>}{s.directPath&&<><small>当前路径：{s.directPath} · {s.directState} · RTT {s.directRttMs} ms</small>{s.directEndpoint&&<small>直连端点：<span className="mono">{s.directEndpoint}</span></small>}<small>直连流量 ↑ {fmtBytes(s.directBytesUp)} / ↓ {fmtBytes(s.directBytesDown)} · 回退 {s.fallbackCount} 次</small>{(s.directSendBps>0||s.directReceiveBps>0)&&<small>QUIC ↑ {fmtBytes(s.directSendBps)}/s · ↓ {fmtBytes(s.directReceiveBps)}/s · 丢包 {s.directPacketLossPct}% · 抖动 {s.directRttDeviationMs} ms · GSO {s.directGso?'ON':'OFF'}</small>}{(s.directUdpReadBufferBytes>0||s.directUdpWriteBufferBytes>0)&&<small>UDP 缓冲 RX {fmtBytes(s.directUdpReadBufferBytes)} · TX {fmtBytes(s.directUdpWriteBufferBytes)}</small>}{s.directError&&<small className="error-text">直连错误：{s.directError}</small>}</>}</td></>}}/></Panel>}
 <Panel title="P2P Direct Path" desc="Client 与 Exit 的路径协商、租约以及回退原因。"><Table columns={['Client → Exit','状态','Client 路径','Exit 路径','租约到期']} items={data.p2p} render={s=><><td><DeviceLabel name={(data.devices.find(d=>d.id===s.clientDeviceId)?.name||s.clientDeviceId)+' → '+(data.devices.find(d=>d.id===s.exitDeviceId)?.name||s.exitDeviceId)} id={s.clientDeviceId+' → '+s.exitDeviceId}/></td><td><Badge tone={s.clientReport?.path==='p2p_quic'&&s.exitReport?.path==='p2p_quic'?'ok':''}>{s.clientReport?.path==='p2p_quic'&&s.exitReport?.path==='p2p_quic'?'DIRECT':s.answered?'已应答':'协商中'}</Badge></td><td>{reportView(s.clientReport)}</td><td>{reportView(s.exitReport)}</td><td>{fmtDate(s.leaseExpiresAt)}</td></>}/></Panel></>;
}
const defaultVerification=()=>({name:'默认验证码',type:'verification_code',default:true,enabled:true,popup:true,match:{matchType:'keywords',keywordMode:'any',keywords:['验证码','短信验证码','校验码','验证代码','确认码','登录码','登录验证码','动态码','动态密码','动态密钥','一次性密码','一次性验证码','安全码','安全验证码','短信码','附加码','登录附加码','认证码','授权码','口令码','OTP','TOTP','verification code','verify code','one-time code','one time code','one-time password','one time password','passcode','security code','authentication code','auth code']},verification:{type:'auto',maxDistance:64,minLength:4,maxLength:8,allowLetters:true,allowDigits:true,requireDigit:true}});
function Messages({ctx}){const {data,run,admin,messageChannel,setMessageChannel}=ctx;const [q,setQ]=useState(''),[kind,setKind]=useState(''),[status,setStatus]=useState('');const matches=list(data.messages).filter(m=>(!messageChannel||m.channelId===messageChannel||m.channel===messageChannel)&&(!kind||(kind==='unmatched'?!m.messageType:m.messageType===kind))&&(!status||list(m.deliveries).some(d=>d.status===status))&&[m.title,m.content,m.body,m.source,m.verificationCode,m.code,m.channelId,...list(m.deliveries).flatMap(d=>[d.deviceName,d.deviceId,d.status])].join(' ').toLowerCase().includes(q.toLowerCase()));return <><Head title="消息历史" desc="查看消息投递、验证码解析和设备状态。" actions={<><Action onClick={()=>ctx.go('channels')}>推送渠道</Action>{admin&&<Action tone="danger" onClick={async()=>{if(confirm('清空选定范围的所有消息？'))await run(()=>api('/messages'+(messageChannel?'?channelId='+encodeURIComponent(messageChannel):''),{method:'DELETE'}),'消息已清空')}}>清除{messageChannel?'此渠道':'全部'}消息</Action>}</>}/><Panel title="消息筛选"><div className="inline-controls"><input className="input" placeholder="搜索标题、来源、正文、验证码" value={q} onChange={e=>setQ(e.target.value)}/><Select value={messageChannel} onChange={setMessageChannel} items={data.channels} placeholder="全部渠道"/><select value={kind} className="input" onChange={e=>setKind(e.target.value)}><option value="">全部类型</option><option value="verification_code">验证码</option><option value="message">普通消息</option><option value="important">重要提醒</option><option value="unmatched">未匹配规则</option></select><select value={status} className="input" onChange={e=>setStatus(e.target.value)}><option value="">全部状态</option>{['delivered','offline','failed','pending'].map(x=><option key={x} value={x}>{x}</option>)}</select></div></Panel><Panel title={'消息记录 · '+matches.length}><Table columns={['时间 / 来源','消息','验证码','目标设备 / 状态','操作']} items={matches} render={m=><><td>{fmtDate(m.createdAt)}<small>{m.source||m.sourceIp||'—'}</small></td><td><b>{m.title||'普通消息'}</b><small style={{whiteSpace:'pre-wrap'}}>{String(m.content||m.body||'').slice(0,160)}</small></td><td className="mono">{m.verificationCode||m.code||'—'}</td><td><DeviceLabel name={m.deviceName||list(m.deliveries).map(x=>x.deviceName||x.deviceId).join('、')||'—'} id={m.deviceId}/><small className="device-delivery-status">{list(m.deliveries).map(x=>x.status).join('、')||'—'}</small></td><td><div className="table-action">{(m.verificationCode||m.code)&&<Action onClick={()=>navigator.clipboard.writeText(m.verificationCode||m.code)}>复制</Action>}{admin&&<Action tone="danger" onClick={async()=>{if(confirm('删除此条消息？'))await run(()=>api('/messages/'+m.id,{method:'DELETE'}),'消息已删除')}}>删除</Action>}</div></td></>}/></Panel></>}
function Channels({ctx}){const {data,run,open,close,admin,setMessageChannel,go}=ctx;const tunnel=data.pushInfo?.tcpListen?data.pushInfo:data.settings?.runtime?.tunnel;return <><Head title="推送渠道" desc="每个渠道属于一个身份；通过自定义渠道 ID 推送消息并按规则分流。" actions={<Action tone="primary" onClick={()=>open('新建推送渠道',<ChannelEditor key="new" ctx={ctx}/>,true)}>新建渠道</Action>}/><div className="grid g2">{data.channels.map(c=><article className="card channel-card" key={c.id}><div className="card-title-area"><DeviceLabel name={c.name} id={c.id}/><Badge>{c.allDevices?'本身份全部设备':list(c.deviceIds).length+' 台兜底设备'}</Badge></div><p className="muted">{list(c.messageRules).length} 条消息规则 · {list(c.routeRules).length} 条内容分流 · {data.identities.find(i=>i.id===c.identityId)?.name||c.identityId||''}</p><div className="channel-url mono">{(pushURL(c.id,tunnel)||'中继地址读取中')}</div><div className="form-actions" style={{marginTop:'auto'}}><Action onClick={()=>{setMessageChannel(c.id);go('messages')}}>查看消息</Action><Action onClick={()=>navigator.clipboard.writeText(pushURL(c.id,tunnel)||'')}>复制接口</Action><Action tone="primary" onClick={()=>open('编辑推送渠道',<ChannelEditor key={c.id} channel={c} ctx={ctx}/>,true)}>编辑</Action></div></article>)}{!data.channels.length&&<div className="card empty-state">尚未创建推送渠道</div>}</div></>}
function MessageRule({rule,onChange,remove,index,move}){
 const m=rule.match||{},v=rule.verification||{};const [keywordsText,setKeywordsText]=useState(()=>list(m.keywords).join(', '));useEffect(()=>setKeywordsText(list(m.keywords).join(', ')),[m.keywords]);const update=(key,value)=>onChange({...rule,[key]:value}),um=(key,value)=>update('match',{...m,[key]:value}),uv=(key,value)=>update('verification',{...v,[key]:value});
 return <div className="rule-card"><div className="card-title-area"><b>{rule.default?'默认验证码规则':'消息规则 '+(index+1)}</b><div className="inline-controls">{!rule.default&&<><Action onClick={()=>move(-1)}>↑</Action><Action onClick={()=>move(1)}>↓</Action><Action tone="danger" onClick={remove}>删除</Action></>}</div></div><div className="form-grid"><Field label="规则名称" value={rule.name||''} onChange={v=>update('name',v)}/>{!rule.default&&<Field label="消息类型" type="select" value={rule.type||'message'} onChange={v=>update('type',v)} options={ [['verification_code','验证码'],['message','普通消息'],['important','重要提醒']] }/>}<Field label="匹配类型" value={m.matchType||'keywords'} onChange={v=>um('matchType',v)} type="select" options={ [['keywords','关键词'],['contains','包含文本'],['regex','正则表达式'],['all','所有消息']] }/>{m.matchType==='keywords'&&<><Field label="关键词（逗号分隔）" value={keywordsText} onChange={setKeywordsText} onBlur={()=>um('keywords',keywordsText.split(/[,，\n]/).map(s=>s.trim()).filter(Boolean))} wide/><Field label="关键词条件" value={m.keywordMode||'any'} type="select" onChange={v=>um('keywordMode',v)} options={ [['any','满足任意'],['all','满足全部']] }/></>}{(m.matchType==='contains'||m.matchType==='regex')&&<Field label="匹配内容" value={m.pattern||''} onChange={v=>um('pattern',v)} wide/>}</div>{rule.type==='verification_code'&&<><hr/><div className="form-grid"><Field label="验证码提取" value={v.type||'auto'} onChange={v=>uv('type',v)} type="select" options={ [['auto','智能识别'],['regex','正则提取']] }/>{v.type==='regex'?<Field label="提取正则" value={v.pattern||''} onChange={val=>uv('pattern',val)}/>:<><Field label="最短长度" type="number" value={v.minLength??4} onChange={val=>uv('minLength',val)}/><Field label="最长长度" type="number" value={v.maxLength??8} onChange={val=>uv('maxLength',val)}/><Field label="关键词最大距离" type="number" value={v.maxDistance??64} onChange={val=>uv('maxDistance',val)}/></>}</div><div className="rule-row">{[['allowLetters','允许字母'],['allowDigits','允许数字'],['requireDigit','至少一个数字']].map(([k,l])=><label key={k}><input type="checkbox" checked={v[k]!==false} onChange={e=>uv(k,e.target.checked)}/> {l}</label>)}</div></>}<div className="rule-row"><label><input type="checkbox" checked={rule.enabled!==false} onChange={e=>update('enabled',e.target.checked)}/> 启用规则</label><label><input type="checkbox" checked={rule.popup!==false} onChange={e=>update('popup',e.target.checked)}/> 命中后弹窗</label><label><input type="checkbox" checked={!!m.caseSensitive} onChange={e=>um('caseSensitive',e.target.checked)}/> 区分大小写</label></div></div>
}
function ChannelEditor({ctx,channel}){
 const {data,run,close,admin}=ctx;const [tab,setTab]=useState('basic');const [name,setName]=useState(channel?.name||''),[id,setId]=useState(channel?.id||''),[identity,setIdentity]=useState(channel?.identityId||(!admin?ctx.user?.identityId:'')||'');
 const [allDevices,setAllDevices]=useState(channel?.allDevices||false),[deviceIds,setDeviceIds]=useState(list(channel?.deviceIds));
 const [rules,setRules]=useState(list(channel?.messageRules).length?structuredClone(channel.messageRules):[defaultVerification()]);const [routes,setRoutes]=useState(structuredClone(list(channel?.routeRules)));
 const scoped=data.devices.filter(d=>d.approvalState==='approved'&&!!identity&&d.identityId===identity);
 const setRule=(i,value)=>setRules(old=>old.map((x,j)=>i===j?value:x));
 const move=(i,n)=>setRules(old=>{const arr=[...old];const dst=i+n;if(dst<0||dst>=arr.length||arr[i].default||arr[dst].default)return old;[arr[i],arr[dst]]=[arr[dst],arr[i]];return arr});
 const submit=async()=>{if(!name.trim())throw Error('渠道名称不能为空');if(id&&!validChannelId(id))throw Error('渠道 ID 只允许 1-80 位字母、数字、点、短横线、下划线');if(admin&&!identity)throw Error('请选择所属身份');if(!allDevices&&!deviceIds.length&&!routes.length)throw Error('请选择兜底设备或添加内容分流规则');if(channel&&channel.id!==id&&!confirm('修改渠道 ID 后旧的推送 URL 会立即失效。继续吗？'))return;
 const body={name:name.trim(),allDevices,deviceIds:allDevices?[]:deviceIds,messageRules:rules,routeRules:routes};if(admin)body.identityId=identity;if(id)body.id=id;
 await run(()=>channel?api('/message-channels/'+encodeURIComponent(channel.id),json('PUT',body)):api('/message-channels',json('POST',body)),'渠道已保存');close();};
 return <><div className="tab-line">{[['basic','基本信息'],['rules','消息规则'],['routes','内容分流']].map(([id,label])=><Action tone={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</Action>)}</div>
 {tab==='basic'&&<><div className="form-grid">{admin&&<Field label="所属身份" value={identity} onChange={v=>{setIdentity(v);setDeviceIds([])}} disabled={!!channel?.identityId} type="select" options={data.identities.map(x=>[x.id,x.name])}/>}<Field label="渠道名称" value={name} onChange={setName} required/><Field label="渠道 ID" value={id} onChange={setId} placeholder="留空由服务端生成" help="编辑 ID 后原推送 URL 将失效"/><div className="toggle-field"><span>未匹配规则时发送到身份全部设备</span><input type="checkbox" checked={allDevices} onChange={e=>setAllDevices(e.target.checked)}/></div></div>{!allDevices&&<><h3>默认 / 兜底设备</h3><div className="form-grid">{scoped.map(d=><label key={d.id} className="toggle-field"><DeviceLabel name={d.name} id={d.id}/><input type="checkbox" checked={deviceIds.includes(d.id)} onChange={e=>setDeviceIds(old=>e.target.checked?[...old,d.id]:old.filter(x=>x!==d.id))}/></label>)}</div></>}<Banner>对外推送接口：<code>{pushURL(id,ctx.data.pushInfo?.tcpListen?ctx.data.pushInfo:ctx.data.settings?.runtime?.tunnel)||'等待中继地址'}</code></Banner></>}
 {tab==='rules'&&<><p className="dialog-note">按顺序匹配。最后一条默认验证码规则可编辑、停用，但总是在最后匹配；只有验证码类型需要提取规则。</p>{rules.map((r,i)=><MessageRule key={i+'-'+!!r.default} rule={r} index={i} onChange={v=>setRule(i,v)} remove={()=>setRules(old=>old.filter((_,j)=>i!==j))} move={n=>move(i,n)}/>)}<Action onClick={()=>setRules(old=>[...old.filter(r=>!r.default),{name:'新消息规则',type:'message',enabled:true,popup:true,match:{matchType:'keywords',keywordMode:'any',keywords:[]}},...old.filter(r=>r.default)])}>+ 新建消息规则</Action></>}
 {tab==='routes'&&<><p className="dialog-note">内容分流先匹配的规则优先，未命中时使用默认 / 兜底设备。</p>{routes.map((r,i)=><div className="rule-card" key={i}><div className="card-title-area"><b>内容分流 {i+1}</b><div className="inline-controls"><Action onClick={()=>setRoutes(old=>{const a=[...old];if(i>0)[a[i-1],a[i]]=[a[i],a[i-1]];return a})}>↑</Action><Action onClick={()=>setRoutes(old=>{const a=[...old];if(i<a.length-1)[a[i+1],a[i]]=[a[i],a[i+1]];return a})}>↓</Action><Action tone="danger" onClick={()=>setRoutes(old=>old.filter((_,j)=>j!==i))}>删除</Action></div></div><div className="form-grid"><Field label="规则名称" value={r.name||''} onChange={v=>setRoutes(old=>old.map((x,j)=>j===i?{...x,name:v}:x))}/><Field label="匹配类型" type="select" value={r.matchType||'contains'} onChange={v=>setRoutes(old=>old.map((x,j)=>j===i?{...x,matchType:v}:x))} options={ [['contains','包含文本'],['regex','正则']] }/><Field label="匹配内容" value={r.pattern||''} onChange={v=>setRoutes(old=>old.map((x,j)=>j===i?{...x,pattern:v}:x))}/></div><div className="rule-row"><label><input type="checkbox" checked={!!r.caseSensitive} onChange={e=>setRoutes(old=>old.map((x,j)=>j===i?{...x,caseSensitive:e.target.checked}:x))}/> 区分大小写</label><label><input type="checkbox" checked={!!r.allDevices} onChange={e=>setRoutes(old=>old.map((x,j)=>j===i?{...x,allDevices:e.target.checked}:x))}/> 全部设备</label></div>{!r.allDevices&&<div className="form-grid">{scoped.map(d=><label className="toggle-field" key={d.id}><DeviceLabel name={d.name} id={d.id}/><input type="checkbox" checked={list(r.deviceIds).includes(d.id)} onChange={e=>setRoutes(old=>old.map((x,j)=>j===i?{...x,deviceIds:e.target.checked?[...list(x.deviceIds),d.id]:list(x.deviceIds).filter(a=>a!==d.id)}:x))}/></label>)}</div>}</div>)}<Action onClick={()=>setRoutes(old=>[...old,{name:'新分流规则',matchType:'contains',pattern:'',deviceIds:[],caseSensitive:false,allDevices:false}])}>+ 新建分流规则</Action></>}
 <div className="form-actions">{channel&&<Action tone="danger" onClick={async()=>{if(confirm('删除渠道后推送 URL 立即失效，确定吗？')){await run(()=>api('/message-channels/'+encodeURIComponent(channel.id),{method:'DELETE'}),'渠道已删除');close()}}}>删除渠道</Action>}<Action tone="primary" onClick={()=>submit().catch(e=>ctx.setError(e.message))}>保存渠道及全部规则</Action></div></>}
function Ingress({ctx}){
 const {data,run,go}=ctx;
 const targets=data.devices.filter(d=>d.approvalState==='approved'&&list(d.approvedCapabilities).includes('rdp.host')&&list(d.approvedCapabilities).includes('rdp.public'));
 const enabled=data.settings?.runtime?.rdpIngress?.enabled===true;
 return <><Head title="RDP 公网入口" desc="固定 TCP/UDP 端口、来源 CIDR、速率限制与目标授权。默认关闭。" actions={<><Action onClick={()=>go('audit')}>连接审计</Action><Action onClick={()=>go('security')}>安全策略</Action><Action tone="primary" disabled={!enabled||!targets.length} onClick={()=>ctx.open('创建 RDP 公网入口',<IngressCreate ctx={ctx} targets={targets}/>) }>＋ 创建入口</Action></>}/>{!enabled&&<Banner type="warn">入口服务当前未启用。先在服务配置中启用并重启 Server。</Banner>}
 <Panel title={'已分配入口 · '+data.ingress.length} desc="入口只向经过能力授权的 RDP 主机转发连接。"><Table columns={['目标设备','端口','来源 CIDR','限速 / 过期','TCP / UDP','状态','操作']} items={data.ingress} render={x=><><td><DeviceLabel name={x.targetName} id={x.targetDeviceId}/></td><td className="mono">{x.listenPort}</td><td className="mono">{list(x.sourceCidrs).join('、')||'全部来源'}</td><td>{x.rateLimitPerMinute} / 分钟<small>{x.expiresAt?fmtDate(x.expiresAt):'永久'}</small></td><td>{x.tcpListening?'TCP ✓':'TCP —'} / {x.udpEnabled?'UDP ✓':'UDP —'}</td><td>{x.status}</td><td><div className="table-action"><Action onClick={()=>run(()=>api('/rdp/ingress/'+encodeURIComponent(x.id)+'/'+(x.status==='enabled'?'disable':'enable'),json('POST',{})),'入口状态已更新')}>{x.status==='enabled'?'停用':'启用'}</Action><Action tone="danger" onClick={()=>{if(confirm('删除该入口并释放监听端口？'))run(()=>api('/rdp/ingress/'+encodeURIComponent(x.id),{method:'DELETE'}),'入口已删除')}}>删除</Action></div></td></>}/></Panel></>;
}
function IngressCreate({ctx,targets}){
 const [target,setTarget]=useState(''),[port,setPort]=useState(''),[cidrs,setCidrs]=useState(''),[rate,setRate]=useState(120),[expires,setExpires]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();if(!target){setError('请选择目标设备');return}setBusy(true);setError('');try{await ctx.run(()=>api('/rdp/ingress',json('POST',{targetDeviceId:target,listenPort:Number(port)||0,sourceCidrs:cidrs.split('\n').map(x=>x.trim()).filter(Boolean),rateLimitPerMinute:Number(rate)||120,...(expires?{expiresAt:isoDate(expires)}:{})})),'RDP 入口已创建');ctx.close()}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <form className="create-dialog-form" onSubmit={submit}><p className="dialog-note">新建后 Server 会绑定固定 TCP/UDP 端口，并应用来源 IP 与速率限制。</p><div className="form-grid"><Field label="目标设备" type="select" value={target} onChange={setTarget} options={[['','请选择目标设备'],...targets.map(x=>[x.id,(x.name||x.id)+(x.name&&x.id?' · '+x.id:'')])]}/><Field label="监听端口（0 自动分配）" type="number" value={port} onChange={setPort}/><Field label="来源 CIDR（每行一条，留空全部来源）" type="lines" value={cidrs} onChange={setCidrs}/><Field label="每来源每分钟连接上限" type="number" value={rate} onChange={setRate}/><Field label="过期时间" type="datetime-local" value={expires} onChange={setExpires}/></div>{error&&<p className="err-notice" role="alert">{error}</p>}<div className="form-actions"><Action onClick={ctx.close} disabled={busy}>取消</Action><Action tone="primary" type="submit" disabled={busy||!targets.length}>{busy?'创建中…':'创建公网入口'}</Action></div></form>
}

function Audit({ctx}){const {run,open}=ctx;const [search,setSearch]=useState(''),[page,setPage]=useState(1),[size,setSize]=useState(20),[result,setResult]=useState({items:[],total:0}),[loading,setLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api('/rdp/security/logs/groups?page='+page+'&pageSize='+size+'&search='+encodeURIComponent(search));setResult(r||{items:[],total:0})}catch(e){ctx.setError(e.message)}finally{setLoading(false)}},[page,size,search,ctx.setError]);useEffect(()=>{load()},[load]);
 const totalPages=Math.max(1,Math.ceil((result.total||0)/size));const erase=async ip=>{if(!confirm(ip?'清除 '+ip+' 的全部连接历史？':'清除所有 RDP 连接记录？封禁和规则不受影响。'))return;await run(()=>api('/rdp/security/logs'+(ip?'?ip='+encodeURIComponent(ip):''),{method:'DELETE'}),'连接记录已清理');load()};
 return <><Head title="RDP 连接审计" desc="按来源 IP 聚合连接，支持目标设备、时间、流量与连接状态明细。" actions={<Action tone="danger" onClick={()=>erase('')}>清除全部记录</Action>}/><Panel title="来源 IP 汇总"><div className="inline-controls"><input className="input" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="搜索 IPv4 / IPv6"/><select className="input" value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1)}}>{[20,50,100].map(n=><option key={n}>{n}</option>)}</select><span className="muted">{loading?'正在读取…':`共 ${result.total||0} 个来源 IP`}</span></div><Table columns={['来源 IP','目标设备','连接 / 拒绝','首访 / 最近连接','流量','操作']} items={list(result.items)} render={item=><><td className="mono">{item.sourceIp}</td><td>{list(item.targets).join('、')||'—'}</td><td>{item.connectionCount??'—'} / {item.rejectedCount??'—'}</td><td>{fmtDate(item.firstSeen)}<small>{fmtDate(item.lastSeen)}</small></td><td>{fmtBytes(item.bytesUp)} / {fmtBytes(item.bytesDown)}</td><td><div className="table-action"><Action onClick={()=>open('连接明细 · '+item.sourceIp,<AuditDetails ip={item.sourceIp} ctx={ctx}/>,true)}>明细</Action><Action onClick={()=>open('封禁来源 IP · '+item.sourceIp,<BanIP ip={item.sourceIp} ctx={ctx}/>)}>封禁</Action><Action tone="danger" onClick={()=>erase(item.sourceIp)}>清除</Action></div></td></>}/><div className="form-actions"><Action disabled={page<=1} onClick={()=>setPage(p=>p-1)}>上一页</Action><span>第 {page} / {totalPages} 页</span><Action disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)}>下一页</Action></div></Panel></>;
}
function BanIP({ip,ctx}){
 const [scope,setScope]=useState(''),[duration,setDuration]=useState(3600),[reason,setReason]=useState('RDP 审计来源 IP 手动封禁'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{
  await ctx.run(()=>api('/rdp/security/bans',json('POST',{cidr:ip,kind:'manual',ingressId:scope,durationSeconds:Number(duration),reason})),'来源 IP 已封禁');ctx.close();
 }catch(err){setError(err.message)}finally{setBusy(false)}};
 return <form onSubmit={submit}><p className="dialog-note">将拒绝来自 <code>{ip}</code> 的新 RDP 连接。可在“IP 安全策略”中随时解封。</p><div className="form-grid"><Field label="来源 IP" value={ip} onChange={()=>{}} disabled/><Field label="作用范围" type="select" value={scope} onChange={setScope} options={ [['','所有 RDP 入口'],...ctx.data.ingress.map(x=>[x.id,x.targetName||x.targetDeviceId||x.id])] }/><Field label="封禁时长" type="select" value={String(duration)} onChange={v=>setDuration(Number(v))} options={ [['900','15 分钟'],['3600','1 小时'],['86400','24 小时'],['604800','7 天'],['0','永久']]} /><Field label="原因" value={reason} onChange={setReason} wide/></div>{error&&<p className="err-notice">{error}</p>}<div className="form-actions"><Action tone="primary" type="submit" disabled={busy}>{busy?'正在封禁…':'确认封禁'}</Action></div></form>
}
function AuditDetails({ip,ctx}){const [page,setPage]=useState(1),[r,setR]=useState({items:[],total:0});useEffect(()=>{api('/rdp/security/logs?ip='+encodeURIComponent(ip)+'&page='+page+'&pageSize=10').then(setR).catch(e=>ctx.setError(e.message))},[ip,page]);return <><Table columns={['连接时间','目标设备','入口','协议','状态 / 原因','流量']} items={list(r.items)} render={x=><><td>{fmtDate(x.startedAt)}</td><td><DeviceLabel name={x.targetName} id={x.targetDeviceId}/></td><td className="mono">{x.ingressId}</td><td>{x.transport}</td><td>{x.result}<small>{x.reason}</small></td><td>{fmtBytes(x.bytesUp)} / {fmtBytes(x.bytesDown)}</td></>}/><div className="form-actions"><Action disabled={page===1} onClick={()=>setPage(x=>x-1)}>上一页</Action><span>{page} / {Math.max(1,Math.ceil((r.total||0)/10))}</span><Action disabled={page>=Math.ceil((r.total||0)/10)} onClick={()=>setPage(x=>x+1)}>下一页</Action></div></>}
function Security({ctx}){const {data,run}=ctx;return <><Head title="RDP IP 安全" desc="黑名单、白名单和自动封禁规则仅对公网 RDP 新连接生效。" actions={<Action tone="primary" onClick={()=>ctx.open('新增 IP 安全策略',<SecurityCreate ctx={ctx}/>)}>＋ 新增 IP 策略</Action>}/><Panel title="活跃 IP 策略" desc="白名单只豁免自动封禁，不能绕过手动封禁、来源 CIDR 和目标授权。"><Table columns={['IP / CIDR','类型','范围','原因','过期时间','操作']} items={data.bans} render={x=><><td className="mono">{x.cidr}</td><td>{x.kind==='manual'?'手动封禁':x.kind==='allow'?'白名单':'自动封禁'}</td><td>{x.ingressId||'全局 RDP'}</td><td>{x.reason||'—'}</td><td>{x.expiresAt?fmtDate(x.expiresAt):'永久'}</td><td><Action tone="danger" onClick={()=>{if(confirm('解除此策略？'))run(()=>api('/rdp/security/bans/'+encodeURIComponent(x.id),{method:'DELETE'}),'策略已解除')}}>解封 / 删除</Action></td></>}/></Panel><Panel title="自动封禁规则" desc="仅统计新的 TCP 连接，达到阈值后拒绝后续新连接。">{data.rules.map(rule=><SecurityRule key={rule.id} rule={rule} ctx={ctx}/>)}</Panel></>}
function SecurityCreate({ctx}){
 const [cidr,setCidr]=useState(''),[kind,setKind]=useState('manual'),[scope,setScope]=useState(''),[duration,setDuration]=useState(0),[reason,setReason]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await ctx.run(()=>api('/rdp/security/bans',json('POST',{cidr:cidr.trim(),kind,ingressId:scope,durationSeconds:Number(duration),reason:reason.trim()})),'IP 策略已生效');ctx.close()}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <form className="create-dialog-form" onSubmit={submit}><p className="dialog-note">可选择封禁或加入自动封禁白名单，新策略仅对后续 RDP 连接生效。</p><div className="form-grid"><Field label="IPv4 / IPv6 / CIDR" value={cidr} onChange={setCidr} required/><Field label="策略" value={kind} onChange={setKind} type="select" options={[['manual','手动封禁'],['allow','自动封禁白名单']]}/><Field label="入口范围" value={scope} onChange={setScope} type="select" options={[['','全部公网入口'],...ctx.data.ingress.map(i=>[i.id,i.targetName||i.id])]}/><Field label="有效期" value={String(duration)} onChange={v=>setDuration(Number(v))} type="select" options={[['900','15 分钟'],['3600','1 小时'],['86400','24 小时'],['604800','7 天'],['0','永久']]}/><Field label="原因" value={reason} onChange={setReason} wide/></div>{error&&<p className="err-notice" role="alert">{error}</p>}<div className="form-actions"><Action onClick={ctx.close} disabled={busy}>取消</Action><Action tone="primary" type="submit" disabled={busy}>{busy?'正在添加…':'确认添加策略'}</Action></div></form>
}

function SecurityRule({rule,ctx}){const [enabled,setEnabled]=useState(rule.enabled),[windowSec,setWindow]=useState(rule.windowSeconds),[threshold,setThreshold]=useState(rule.threshold),[banSec,setBan]=useState(rule.banSeconds);return <div className="rule-card"><div className="card-title-area"><b>{rule.name}</b><span className="mono muted">{rule.id}</span></div><div className="form-grid"><Field label="启用" type="checkbox" value={enabled} onChange={setEnabled}/><Field label="统计窗口（秒）" type="number" value={windowSec} onChange={setWindow}/><Field label="连接阈值" type="number" value={threshold} onChange={setThreshold}/><Field label="封禁时长（秒）" type="number" value={banSec} onChange={setBan}/></div><div className="form-actions"><Action tone="primary" onClick={()=>ctx.run(()=>api('/rdp/security/rules/'+rule.id,json('PUT',{enabled,windowSeconds:Number(windowSec),threshold:Number(threshold),banSeconds:Number(banSec)})),'自动封禁规则已保存')}>保存规则</Action></div></div>}
function Settings({ctx}){
 const {data,admin,run,draft,setDraft,saved,setSaved,saving,setSaving,settingsTab,setSettingsTab}=ctx;
 const group=getGroup(settingsTab),key=group.key||group.id;
 const change=(field,val)=>setDraft(old=>({...old,__pending:true,[key]:{...old[key],[field]:val}}));
 const save=async()=>{if(!saved?.config||!draft)return;try{validatePortRange(draft);setSaving(true);const config=normalizeForSave(draft,saved.config);const result=await api('/server/config',json('PUT',{revision:saved.revision,config}));setSaved(result);setDraft(result.config);ctx.flash(result.restartRequired?'配置已保存，重启 Server 后生效':'配置已保存');ctx.refresh()}catch(e){ctx.setError(e.status===409?e.message+'。请先备份当前修改，再刷新以读取最新版本。':e.message)}finally{setSaving(false)}};
 const clean=!!saved?.config&&!!draft&&configEqual(draft,saved.config);
 if(!admin)return null;
 if(!draft||!saved?.config)return <div className="empty-state">服务配置正在读取。<Action onClick={ctx.refresh}>重试</Action></div>;
 return <><Head title="服务配置" desc="集中管理管理端、隧道、直连、出口及安全策略。保存前可以切换配置分类。"/><div className="settings-layout"><aside className="settings-sidebar">{[...new Set(groups.map(g=>g.section))].map(section=><div className="settings-nav-group" key={section}><div className="settings-nav-label">{section}</div>{groups.filter(g=>g.section===section).map(g=><button type="button" key={g.id} className={'settings-nav-item '+(g.id===settingsTab?'active':'')} onClick={()=>{setSettingsTab(g.id);history.replaceState(null,'','#settings/'+g.id)}}><span className="settings-nav-icon">⚙</span><span><b>{g.title}</b><small>{g.subtitle}</small></span></button>)}</div>)}</aside><div className="settings-main"><div className="settings-heading"><div className="settings-kicker">SERVER SETTINGS / {group.section}</div><h2>{group.title}</h2><p>{group.subtitle}</p></div><div className="config-card"><div className="config-card-head"><span className="config-card-icon">⚙</span><div className="config-card-heading"><h3>{group.title}参数</h3><p>配置项保存后根据运行时要求生效</p></div><Badge tone={clean?'ok':''}>{clean?'已同步':'待保存'}</Badge></div><div className="config-card-content"><div className="config-form-grid">{group.fields.map(([field,label,type,placeholder,opts])=>{const isEnable=type==='checkbox'&&field==='enabled';const disabled=(group.id==='direct'||group.id==='exit'||group.id==='rdp')&&!draft[key]?.enabled&&field!=='enabled';const proxy=(key==='serverExit'&&['upstreamAddress','upstreamUsername','upstreamPassword'].includes(field)&&draft.serverExit?.upstreamMode==='direct');return <div key={field} className={type==='lines'?'wide':''}><Field label={label} type={type} value={draft[key]?.[field]} placeholder={placeholder} options={opts} disabled={disabled||proxy||saving} onChange={v=>change(field,v)} wide={type==='lines'}/></div>})}</div>{group.id==='admin'&&<Banner>管理台访问地址变化后需使用新的端口和协议重新访问。隧道监听地址不受此设置影响。</Banner>}{group.id==='p2p'&&<Banner>UPnP 在 Agent 所在路由器上尝试映射。Rendezvous 是服务端 UDP 反射地址；端口设置为 0 / 0 时使用随机端口。</Banner>}{group.id==='direct'&&<Banner>Public Direct 对公网端点进行验证，验证成功后才会向获授权客户端下发短期连接 Ticket。</Banner>}{group.id==='rdp'&&<Banner>启用公网 RDP 入口后仍需创建目标入口并显式授权设备能力。连接记录和封禁策略在 RDP 页面管理。</Banner>}{group.id==='exit'&&<SystemGrants ctx={ctx}/ >}{group.id==='acl'&&<Banner>allow 模式下空列表可能拒绝全部目标；出口设备本地限制仍生效。</Banner>}{group.id==='certificate'&&<Banner>路径均是 Server 运行环境内的文件路径，证书更改需要重启。</Banner>}</div></div><div className="settings-save"><div><strong>{saving?'保存中…':clean?'没有未保存的修改':'有未保存的修改'}</strong><small className="muted"> · 版本 {saved.revision} · {saved.configPath||'Server config'}</small></div><div className="actions"><Action disabled={clean||saving} onClick={()=>setDraft(structuredClone(saved.config))}>放弃修改</Action><Action tone="primary" disabled={clean||saving} onClick={save}>保存配置</Action></div></div></div></div></>;
}
function SystemGrants({ctx}){
 const {data,run}=ctx;
 const grants=data.systemGrants.filter(g=>g.resourceId==='server');
 const edit=g=>ctx.open(g?'编辑 Server Exit 身份授权':'授权 Server Exit 身份',<SystemGrantEditor ctx={ctx} grant={g}/>);
 return <div className="config-card" style={{marginTop:14}}><div className="config-card-head"><div className="config-card-heading"><h3>Server Exit 身份授权</h3><p>只有被明确授权的身份才能使用系统出口 server。</p></div><Action tone="primary" onClick={()=>edit(null)}>＋ 授权身份</Action></div><div className="config-card-content"><Table columns={['身份','能力','过期时间','版本','操作']} items={grants} render={g=><><td>{g.granteeIdentityName||g.granteeIdentityId}</td><td>Proxy 出口</td><td>{g.expiresAt?fmtDate(g.expiresAt):'永久'}</td><td>{g.revision}</td><td><div className="table-action"><Action onClick={()=>edit(g)}>编辑</Action><Action tone="danger" onClick={()=>{if(confirm('删除此身份授权？'))run(()=>api('/system-identity-grants/'+g.id+'?revision='+g.revision,{method:'DELETE'}),'授权已撤销')}}>删除</Action></div></td></>}/></div></div>
}
function SystemGrantEditor({ctx,grant}){
 const [identity,setIdentity]=useState(grant?.granteeIdentityId||'');
 const [expires,setExpires]=useState(localDate(grant?.expiresAt));
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const submit=async e=>{e.preventDefault();if(!identity){setError('请选择身份');return}setBusy(true);setError('');const body={granteeIdentityId:identity,features:['proxy.use']};if(expires)body.expiresAt=isoDate(expires);try{await ctx.run(()=>grant?api('/system-identity-grants/'+encodeURIComponent(grant.id),json('PATCH',{...body,...(!expires?{clearExpiresAt:true}:{}),revision:grant.revision})):api('/system-identity-grants',json('POST',{...body,expiresAt:body.expiresAt||'',resourceId:'server'})),'Server Exit 授权已保存');ctx.close()}catch(err){setError(err.message)}finally{setBusy(false)}};
 return <form className="create-dialog-form" onSubmit={submit}><p className="dialog-note">仅增加 Server Exit 的 proxy.use 能力授权；设备本身仍需满足对应身份和 ACL 限制。</p><div className="form-grid"><Field label="被授权身份" type="select" value={identity} onChange={setIdentity} disabled={!!grant} options={[['','请选择身份'],...ctx.data.identities.map(x=>[x.id,x.name])]}/><Field label="过期时间（留空永久）" type="datetime-local" value={expires} onChange={setExpires}/></div>{error&&<p className="err-notice" role="alert">{error}</p>}<div className="form-actions"><Action disabled={busy} onClick={ctx.close}>取消</Action><Action tone="primary" type="submit" disabled={!identity||busy}>{busy?'保存中…':grant?'保存授权':'授权身份'}</Action></div></form>
}
