package main

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"relayproxy/internal/config"
)

const agentConfigName = "relay-agent.yaml"

func resolveConfigPath(requested string, explicit bool) (string, error) {
	if explicit {
		if strings.TrimSpace(requested) == "" {
			return "", fmt.Errorf("--config must specify a file path")
		}
		return filepath.Abs(requested)
	}
	path, err := defaultConfigPath()
	if err != nil {
		return "", err
	}
	if runtime.GOOS == "windows" || runtime.GOOS == "darwin" {
		return selectDefaultConfigPath(path, legacyConfigPaths()), nil
	}
	return path, nil
}

// New desktop installations store mutable settings in the user profile, but
// existing installations may still have their settings beside the executable.
// Reuse that file in place: its sibling device-identity.json must remain with
// the configuration, or the server would see a different device on upgrade.
func defaultConfigPath() (string, error) {
	if runtime.GOOS == "windows" || runtime.GOOS == "darwin" {
		homeDir, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("get user home directory: %w", err)
		}
		if !filepath.IsAbs(homeDir) {
			return "", fmt.Errorf("user home directory must be an absolute path")
		}
		return filepath.Join(homeDir, ".relayproxy", agentConfigName), nil
	}
	return filepath.Abs(filepath.Join("configs", agentConfigName))
}

func legacyConfigPaths() []string {
	var paths []string
	if executable, err := os.Executable(); err == nil {
		dir := filepath.Dir(executable)
		paths = append(paths,
			filepath.Join(dir, "configs", agentConfigName),
			filepath.Join(dir, agentConfigName),
		)
		// macOS .app bundles keep the Agent in Contents/Resources, while the
		// release archive places configs/ next to RelayProxy.app.
		if runtime.GOOS == "darwin" && filepath.Base(dir) == "Resources" && filepath.Base(filepath.Dir(dir)) == "Contents" {
			appDir := filepath.Dir(filepath.Dir(dir))
			paths = append(paths, filepath.Join(filepath.Dir(appDir), "configs", agentConfigName))
		}
	}
	if cwd, err := os.Getwd(); err == nil {
		paths = append(paths,
			filepath.Join(cwd, "configs", agentConfigName),
			filepath.Join(cwd, agentConfigName),
		)
	}
	return paths
}

// selectDefaultConfigPath has no write side effects. A real profile config
// always wins. An untouched bootstrap generated by a previous broken launch
// must not mask an older configured file. Existing legacy files are loaded
// in place instead of copied, keeping identity and user edits together.
func selectDefaultConfigPath(primary string, legacy []string) string {
	data, err := os.ReadFile(primary)
	if err == nil && !isBootstrapConfig(data) {
		return primary
	}
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		// The loader will surface the actual permission/IO error. Never
		// silently substitute a new default configuration.
		return primary
	}
	seen := map[string]bool{filepath.Clean(primary): true}
	firstBootstrap := ""
	for _, candidate := range legacy {
		candidate = filepath.Clean(candidate)
		if seen[candidate] {
			continue
		}
		seen[candidate] = true
		old, readErr := os.ReadFile(candidate)
		if errors.Is(readErr, os.ErrNotExist) {
			continue
		}
		if readErr != nil {
			// Existing-but-unreadable configuration must produce an error
			// rather than allowing a new identity/config to be generated.
			return candidate
		}
		if isPackagedExample(old) {
			continue
		}
		if isBootstrapConfig(old) {
			if firstBootstrap == "" {
				firstBootstrap = candidate
			}
			continue
		}
		return candidate
	}
	if errors.Is(err, os.ErrNotExist) && firstBootstrap != "" {
		return firstBootstrap
	}
	return primary
}

func isBootstrapConfig(contents []byte) bool {
	return bytes.Equal(bytes.TrimSpace(contents), []byte("server:\n    address: 127.0.0.1"))
}

// Release packages contain a sample configs/relay-agent.yaml. It must not
// silently override the real profile configuration or become a user's identity.
func isPackagedExample(contents []byte) bool {
	return bytes.Contains(contents, []byte("address: relay.example.com")) &&
		bytes.Contains(contents, []byte("identity_id: a1b2c3d4e5f6g7h8"))
}

// loadOrCreateAgentConfig runs before the agent starts, under its instance
// lock. Existing or invalid files are never replaced by generated defaults.
// Legacy discovery is done by resolveConfigPath; this function only loads.
func loadOrCreateAgentConfig(path string) (*config.AgentConfigFile, error) {
	cfg, err := config.LoadAgentConfig(path)
	if err == nil {
		return cfg, nil
	}
	if !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}

	cfg = defaultConfigFile()
	if err := config.NormalizeAgentConfig(cfg); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0700); err != nil {
		return nil, fmt.Errorf("create configuration directory: %w", err)
	}
	if err := config.SaveBootstrapAgentConfig(path, cfg.Server.Address); err != nil {
		return nil, err
	}
	return cfg, nil
}
