// Package secure contains the small, memory-only authentication codecs used
// by the RDP direct path.  The server never stores these keys: a key exists
// only for the lifetime of one rendezvous session.
package secure

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/binary"
	"errors"
	"fmt"
	"hash"
	"sync"
)

const (
	PunchMagic   uint32 = 0x52504433 // "RPD3"
	DataMagic    uint32 = 0x52504444 // "RPDD"
	WireVersion  byte   = 1
	PunchRequest byte   = 1
	PunchAck     byte   = 2
	PunchKeep    byte   = 3

	punchSize      = 40
	dataHead       = 24 // magic, version, flags, session id, sequence, payload size
	macSize        = 16
	MaxDataPayload = 65467 // leaves the 40-byte authentication header in 65507
)

var (
	ErrInvalidPacket = errors.New("invalid RDP direct-path packet")
	ErrBadMAC        = errors.New("invalid RDP direct-path authentication tag")
	ErrReplay        = errors.New("replayed RDP direct-path packet")
	ErrShortBuffer   = errors.New("RDP direct-path packet is larger than the receive buffer")
)

type Domain string

const (
	DomainRDP          Domain = "rdp"
	DomainDesktopMedia Domain = "desktop_media"
)

func punchDomain(domain Domain) ([]byte, error) {
	switch domain {
	case DomainRDP:
		return []byte("relayproxy-rdp-punch\x00"), nil
	case DomainDesktopMedia:
		return []byte("relayproxy-desktop-media-punch\x00"), nil
	default:
		return nil, fmt.Errorf("unsupported direct-path security domain %q", domain)
	}
}

func dataDomain(domain Domain) ([]byte, error) {
	switch domain {
	case DomainRDP:
		return []byte("relayproxy-rdp-data\x00"), nil
	case DomainDesktopMedia:
		return []byte("relayproxy-desktop-media-data\x00"), nil
	default:
		return nil, fmt.Errorf("unsupported direct-path security domain %q", domain)
	}
}

// PunchPacket is an authenticated discovery packet.  Nonce is generated by
// the sender and is echoed by the peer in the acknowledgement.
type PunchPacket struct {
	Type      byte
	SessionID uint64
	Nonce     uint64
}

func punchMAC(key []byte, domain Domain, p PunchPacket) ([macSize]byte, error) {
	var out [macSize]byte
	domainBytes, err := punchDomain(domain)
	if err != nil {
		return out, err
	}
	var b [22]byte
	b[0] = p.Type
	b[1] = WireVersion
	binary.BigEndian.PutUint64(b[2:10], p.SessionID)
	binary.BigEndian.PutUint64(b[10:18], p.Nonce)
	h := hmac.New(sha256.New, key)
	_, _ = h.Write(domainBytes)
	_, _ = h.Write(b[:18])
	copy(out[:], h.Sum(nil)[:macSize])
	return out, nil
}

// Encode serializes a punch packet and authenticates its session, type and
// nonce.  key must be the random session token from the coordinator.
func (p PunchPacket) Encode(key []byte) []byte {
	packet, _ := p.EncodeWithDomain(key, DomainRDP)
	return packet
}

func (p PunchPacket) EncodeWithDomain(key []byte, domain Domain) ([]byte, error) {
	mac, err := punchMAC(key, domain, p)
	if err != nil {
		return nil, err
	}
	buf := make([]byte, punchSize)
	binary.BigEndian.PutUint32(buf[0:4], PunchMagic)
	buf[4] = WireVersion
	buf[5] = p.Type
	binary.BigEndian.PutUint64(buf[6:14], p.SessionID)
	binary.BigEndian.PutUint64(buf[14:22], p.Nonce)
	copy(buf[24:], mac[:])
	return buf, nil
}

func DecodePunchPacket(raw []byte, key []byte) (PunchPacket, error) {
	return DecodePunchPacketWithDomain(raw, key, DomainRDP)
}

func DecodePunchPacketWithDomain(raw []byte, key []byte, domain Domain) (PunchPacket, error) {
	if len(raw) != punchSize || binary.BigEndian.Uint32(raw[0:4]) != PunchMagic || raw[4] != WireVersion {
		return PunchPacket{}, ErrInvalidPacket
	}
	p := PunchPacket{Type: raw[5], SessionID: binary.BigEndian.Uint64(raw[6:14]), Nonce: binary.BigEndian.Uint64(raw[14:22])}
	if p.Type != PunchRequest && p.Type != PunchAck && p.Type != PunchKeep {
		return PunchPacket{}, ErrInvalidPacket
	}
	want, err := punchMAC(key, domain, p)
	if err != nil {
		return PunchPacket{}, err
	}
	if !hmac.Equal(raw[24:], want[:]) {
		return PunchPacket{}, ErrBadMAC
	}
	return p, nil
}

// DataCodec authenticates RDP UDP payloads.  It includes a monotonically
// increasing sequence and a bounded replay window.  Each direction owns one
// codec; no counters are persisted.
type DataCodec struct {
	mu      sync.Mutex
	key     []byte
	session uint64
	next    uint64
	highest uint64
	seen    uint64
	started bool
	mac     hash.Hash
	macBuf  [sha256.Size]byte
	domain  []byte
}

func NewDataCodec(sessionID uint64, key []byte) (*DataCodec, error) {
	return NewDataCodecWithDomain(sessionID, key, DomainRDP)
}

func NewDataCodecWithDomain(sessionID uint64, key []byte, domain Domain) (*DataCodec, error) {
	if sessionID == 0 || len(key) < 16 {
		return nil, fmt.Errorf("direct-path data codec requires a session id and a 128-bit key")
	}
	domainBytes, err := dataDomain(domain)
	if err != nil {
		return nil, err
	}
	keyCopy := append([]byte(nil), key...)
	return &DataCodec{
		session: sessionID,
		key:     keyCopy,
		mac:     hmac.New(sha256.New, keyCopy),
		domain:  append([]byte(nil), domainBytes...),
	}, nil
}

func (c *DataCodec) Encode(payload []byte) ([]byte, error) {
	return c.EncodeTo(nil, payload)
}

// EncodeTo writes one authenticated packet into dst. The returned slice is
// backed by dst when it has sufficient capacity, allowing callers that own a
// single writer to avoid a heap allocation for every datagram.
func (c *DataCodec) EncodeTo(dst, payload []byte) ([]byte, error) {
	if len(payload) > MaxDataPayload {
		return nil, fmt.Errorf("RDP data payload exceeds %d bytes", MaxDataPayload)
	}
	total := dataHead + len(payload) + macSize
	if cap(dst) < total {
		dst = make([]byte, total)
	} else {
		dst = dst[:total]
	}
	c.mu.Lock()
	seq := c.next
	c.next++
	binary.BigEndian.PutUint32(dst[0:4], DataMagic)
	dst[4] = WireVersion
	dst[5] = 0 // reserved flags
	binary.BigEndian.PutUint64(dst[6:14], c.session)
	binary.BigEndian.PutUint64(dst[14:22], seq)
	binary.BigEndian.PutUint16(dst[22:24], uint16(len(payload)))
	copy(dst[dataHead:], payload)
	mac := c.macLocked(dst[:dataHead+len(payload)])
	copy(dst[dataHead+len(payload):], mac[:])
	c.mu.Unlock()
	return dst, nil
}

func (c *DataCodec) Decode(raw []byte) ([]byte, error) {
	if len(raw) < dataHead+macSize || binary.BigEndian.Uint32(raw[0:4]) != DataMagic || raw[4] != WireVersion || raw[5] != 0 {
		return nil, ErrInvalidPacket
	}
	n := int(binary.BigEndian.Uint16(raw[22:24]))
	if n > MaxDataPayload || len(raw) != dataHead+n+macSize {
		return nil, ErrInvalidPacket
	}
	dst := make([]byte, n)
	decoded, err := c.DecodeTo(raw, dst)
	if err != nil {
		return nil, err
	}
	return dst[:decoded], nil
}

// DecodeTo authenticates raw and copies its payload into dst. It returns
// ErrShortBuffer before mutating replay state when dst is too small.
func (c *DataCodec) DecodeTo(raw, dst []byte) (int, error) {
	if len(raw) < dataHead+macSize || binary.BigEndian.Uint32(raw[0:4]) != DataMagic || raw[4] != WireVersion || raw[5] != 0 {
		return 0, ErrInvalidPacket
	}
	if binary.BigEndian.Uint64(raw[6:14]) != c.session {
		return 0, ErrInvalidPacket
	}
	n := int(binary.BigEndian.Uint16(raw[22:24]))
	if n > MaxDataPayload || len(raw) != dataHead+n+macSize {
		return 0, ErrInvalidPacket
	}
	if len(dst) < n {
		return 0, ErrShortBuffer
	}
	seq := binary.BigEndian.Uint64(raw[14:22])
	c.mu.Lock()
	defer c.mu.Unlock()
	mac := c.macLocked(raw[:dataHead+n])
	if !hmac.Equal(raw[dataHead+n:], mac[:]) {
		return 0, ErrBadMAC
	}
	if c.started {
		switch {
		case seq > c.highest:
			shift := seq - c.highest
			if shift >= 64 {
				c.seen = 1
			} else {
				c.seen = (c.seen << shift) | 1
			}
			c.highest = seq
		case c.highest-seq >= 64:
			return 0, ErrReplay
		case c.seen&(uint64(1)<<(c.highest-seq)) != 0:
			return 0, ErrReplay
		default:
			c.seen |= uint64(1) << (c.highest - seq)
		}
	} else {
		c.started, c.highest, c.seen = true, seq, 1
	}
	copy(dst[:n], raw[dataHead:dataHead+n])
	return n, nil
}

func (c *DataCodec) macLocked(raw []byte) [macSize]byte {
	c.mac.Reset()
	_, _ = c.mac.Write(c.domain)
	_, _ = c.mac.Write(raw)
	sum := c.mac.Sum(c.macBuf[:0])
	var out [macSize]byte
	copy(out[:], sum[:macSize])
	return out
}
