//go:build windows

package gui

import (
	"fmt"
	"io/fs"
	"strings"
	"testing/fstest"

	"relayproxy/internal/webui"
)

// buildReactWailsAssets loads the Vite output when it has been generated by
// agent/gui/frontend. The checked-in react_dist/README.txt keeps go:embed valid,
// while ordinary Go-only development can still fall back to the legacy page.
func buildReactWailsAssets(opts Options) (string, string, fstest.MapFS, bool, error) {
	index, err := assets.ReadFile("react_dist/index.html")
	if err != nil {
		if strings.Contains(err.Error(), "file does not exist") || strings.Contains(err.Error(), "no such file") {
			return "", "", nil, false, nil
		}
		return "", "", nil, false, err
	}

	files := fstest.MapFS{}
	err = fs.WalkDir(assets, "react_dist", func(path string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() || path == "react_dist/README.txt" {
			return nil
		}
		data, readErr := assets.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		name := strings.TrimPrefix(path, "react_dist/")
		files[name] = &fstest.MapFile{Data: data, Mode: 0o444}
		return nil
	})
	if err != nil {
		return "", "", nil, false, fmt.Errorf("读取 React 构建产物失败: %w", err)
	}

	connections, err := renderConnectionsHTML(opts.theme() == "dark" || (opts.theme() == "system" && systemPrefersDark()))
	if err != nil {
		return "", "", nil, false, err
	}
	connectionsJS, err := assets.ReadFile("assets/connections.js")
	if err != nil {
		return "", "", nil, false, err
	}
	bridgeJS, err := assets.ReadFile("assets/wails-bridge.js")
	if err != nil {
		return "", "", nil, false, err
	}
	verificationHTML, err := assets.ReadFile("assets/verification.html")
	if err != nil {
		return "", "", nil, false, err
	}
	baseCSS, err := webui.ReadAsset("base.css")
	if err != nil {
		return "", "", nil, false, err
	}
	themeJS, err := webui.ReadAsset("theme.js")
	if err != nil {
		return "", "", nil, false, err
	}

	inject := "<link rel=\"stylesheet\" href=\"/ui/base.css\">" +
		"<script src=\"/ui/theme.js\"></script>" +
		"<script src=\"/wails/runtime.js\" type=\"module\"></script>" +
		"<script src=\"/wails-bridge.js\" defer></script>"
	connections = strings.Replace(connections, "<head>", "<head>"+inject, 1)

	files["connections.js"] = &fstest.MapFile{Data: connectionsJS, Mode: 0o444}
	files["wails-bridge.js"] = &fstest.MapFile{Data: bridgeJS, Mode: 0o444}
	files["verification.html"] = &fstest.MapFile{Data: verificationHTML, Mode: 0o444}
	files["ui/base.css"] = &fstest.MapFile{Data: baseCSS, Mode: 0o444}
	files["ui/theme.js"] = &fstest.MapFile{Data: themeJS, Mode: 0o444}

	mode := opts.theme()
	dark := mode == "dark" || (mode == "system" && systemPrefersDark())
	classAttr := ""
	if dark {
		classAttr = " class=\"dark\""
	}
	mainHTML := string(index)
	mainHTML = strings.Replace(
		mainHTML,
		"<html lang=\"zh-CN\" data-theme-mode=\"system\">",
		"<html lang=\"zh-CN\""+classAttr+" data-theme-mode=\""+mode+"\" data-theme=\""+map[bool]string{true: "dark", false: "light"}[dark]+"\">",
		1,
	)
	return mainHTML, connections, files, true, nil
}
