package repository

import (
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

// RDPTarget is the server-side view of an approved target. Its local address
// is intentionally not exposed to controllers; the target Agent owns that
// configuration and always dials its own RDP service.
type RDPTarget struct {
	DeviceID string    `json:"deviceId"`
	Name     string    `json:"name"`
	Online   bool      `json:"online"`
	Service  string    `json:"-"` // internal service lookup; never exposed to controllers
	Port     int       `json:"-"` // target-local port; never exposed to controllers
	Updated  time.Time `json:"-"`
}

func (db *DB) ListRDPTargetsForController(controllerID string) ([]*RDPTarget, error) {
	if controllerID == "" {
		return nil, errors.New("controller device id is required")
	}
	var controllerCaps string
	var controllerIdentity sql.NullString
	if err := db.QueryRow(`SELECT approved_capabilities, identity_id FROM devices
		WHERE id = ? AND approval_state = 'approved'`, controllerID).Scan(&controllerCaps, &controllerIdentity); err != nil {
		return nil, err
	}
	if !hasCapabilityJSON(controllerCaps, "rdp.controller") {
		return []*RDPTarget{}, nil
	}

	var rows *sql.Rows
	var err error
	if controllerIdentity.Valid && strings.TrimSpace(controllerIdentity.String) != "" {
		rows, err = db.Query(`SELECT target.id, target.name, target.last_seen_at, target.approved_capabilities,
			service.id, service.target_port, service.updated_at
			FROM devices target
			JOIN identities identity ON identity.id = target.identity_id AND identity.status = ?
			JOIN rdp_services service ON service.device_id = target.id AND service.enabled = TRUE
			WHERE target.identity_id = ?
			  AND target.id <> ?
			  AND target.approval_state = 'approved'
			ORDER BY target.name, target.id`,
			IdentityStatusActive, controllerIdentity.String, controllerID)
	} else {
		// Legacy v3 devices retain explicit per-controller grants during migration.
		rows, err = db.Query(`SELECT target.id, target.name, target.last_seen_at, target.approved_capabilities,
			service.id, service.target_port, service.updated_at
			FROM rdp_access_grants access
			JOIN devices controller ON controller.id = access.controller_device_id
			JOIN devices target ON target.id = access.target_device_id
			JOIN rdp_services service ON service.device_id = target.id AND service.enabled = TRUE
			WHERE access.controller_device_id = ?
			  AND controller.approval_state = 'approved'
			  AND target.approval_state = 'approved'
			  AND controller.identity_id IS NULL
			  AND target.identity_id IS NULL
			  AND controller.owner_user_id IS NOT NULL
			  AND controller.owner_user_id = target.owner_user_id
			ORDER BY target.name, target.id`, controllerID)
	}
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := make([]*RDPTarget, 0)
	for rows.Next() {
		item := &RDPTarget{}
		var lastSeen sql.NullTime
		var targetCaps string
		if err := rows.Scan(&item.DeviceID, &item.Name, &lastSeen, &targetCaps, &item.Service, &item.Port, &item.Updated); err != nil {
			return nil, err
		}
		if !hasCapabilityJSON(targetCaps, "rdp.host") {
			continue
		}
		item.Online = lastSeen.Valid && time.Since(lastSeen.Time) <= 2*time.Minute
		result = append(result, item)
	}
	return result, rows.Err()
}

// ensureExplicitRDPGrantModel converts the previous same-owner auto-grant
// matrix to default-deny exactly once. Before this release there was no API/UI
// for creating per-target grants, so existing rows were generated by
// syncOwnerRDPGrants and must not survive the authorization model change.
func (db *DB) ensureExplicitRDPGrantModel() error {
	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	if _, err := tx.Exec(`CREATE TABLE IF NOT EXISTS server_migrations (
		name VARCHAR(100) PRIMARY KEY,
		applied_at TIMESTAMP NOT NULL
	)`); err != nil {
		return err
	}
	var migrated int
	if err := tx.QueryRow(`SELECT COUNT(*) FROM server_migrations WHERE name = 'rdp.explicit_grants.v1'`).Scan(&migrated); err != nil {
		return err
	}
	if migrated > 0 {
		return tx.Commit()
	}
	if _, err := tx.Exec(`DELETE FROM rdp_access_grants`); err != nil {
		return err
	}
	now := time.Now().UTC()
	if _, err := tx.Exec(`INSERT INTO server_migrations (name, applied_at) VALUES ('rdp.explicit_grants.v1', ?)`, now); err != nil {
		return err
	}
	if err := insertAuthorizationAudit(tx, "rdp.explicit_grants.v1", "system", "system", "rdp_access_grants",
		map[string]any{"mode": "explicit", "default": "deny"}, now); err != nil {
		return err
	}
	return tx.Commit()
}

// ReplaceRDPTargetGrants atomically replaces the explicit RDP target set for
// one controller. An empty target list is valid and means the controller may
// not discover or connect to any RDP host.
func (db *DB) ReplaceRDPTargetGrants(controllerID, reviewerID string, targetIDs []string) ([]*RDPTarget, error) {
	controllerID = strings.TrimSpace(controllerID)
	reviewerID = strings.TrimSpace(reviewerID)
	if controllerID == "" || reviewerID == "" {
		return nil, errors.New("controller device id and reviewer id are required")
	}

	tx, err := db.Begin()
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	var controllerOwner, controllerIdentity sql.NullString
	var controllerCaps string
	if err := tx.QueryRow(`SELECT owner_user_id, identity_id, approved_capabilities FROM devices
		WHERE id = ? AND approval_state = 'approved'`, controllerID).Scan(&controllerOwner, &controllerIdentity, &controllerCaps); err != nil {
		return nil, err
	}
	if controllerIdentity.Valid && strings.TrimSpace(controllerIdentity.String) != "" {
		return nil, errors.New("identity-managed RDP controllers use automatic same-identity access")
	}
	if !controllerOwner.Valid || strings.TrimSpace(controllerOwner.String) == "" {
		return nil, errors.New("RDP controller has no owner")
	}
	if !hasCapabilityJSON(controllerCaps, "rdp.controller") {
		return nil, errors.New("device is not approved as an RDP controller")
	}

	normalized := make([]string, 0, len(targetIDs))
	seen := make(map[string]struct{}, len(targetIDs))
	for _, raw := range targetIDs {
		targetID := strings.TrimSpace(raw)
		if targetID == "" {
			continue
		}
		if targetID == controllerID {
			return nil, errors.New("an RDP controller cannot target itself")
		}
		if _, exists := seen[targetID]; exists {
			continue
		}
		seen[targetID] = struct{}{}

		var targetOwner sql.NullString
		var targetCaps string
		var serviceEnabled int
		err := tx.QueryRow(`SELECT target.owner_user_id, target.approved_capabilities,
			CASE WHEN EXISTS (SELECT 1 FROM rdp_services service WHERE service.device_id = target.id AND service.enabled = TRUE) THEN 1 ELSE 0 END
			FROM devices target WHERE target.id = ? AND target.approval_state = 'approved'`, targetID).
			Scan(&targetOwner, &targetCaps, &serviceEnabled)
		if errors.Is(err, sql.ErrNoRows) {
			return nil, fmt.Errorf("RDP target %q was not found", targetID)
		}
		if err != nil {
			return nil, err
		}
		if !targetOwner.Valid || targetOwner.String != controllerOwner.String || !hasCapabilityJSON(targetCaps, "rdp.host") || serviceEnabled != 1 {
			return nil, fmt.Errorf("RDP target %q is not an available host for this controller", targetID)
		}
		normalized = append(normalized, targetID)
	}

	if _, err := tx.Exec(`DELETE FROM rdp_access_grants WHERE controller_device_id = ?`, controllerID); err != nil {
		return nil, err
	}
	now := time.Now().UTC()
	for _, targetID := range normalized {
		if _, err := tx.Exec(`INSERT INTO rdp_access_grants
			(controller_device_id, target_device_id, granted_by, created_at) VALUES (?, ?, ?, ?)`,
			controllerID, targetID, reviewerID, now); err != nil {
			return nil, err
		}
	}
	if err := insertAuthorizationAudit(tx, "rdp.targets.replace", reviewerID, "device", controllerID,
		map[string]any{"targetDeviceIds": normalized}, now); err != nil {
		return nil, err
	}
	if err := tx.Commit(); err != nil {
		return nil, err
	}
	return db.ListRDPTargetsForController(controllerID)
}

// AuthorizeRDP is the only server-side admission check for a controller to
// target connection. Both devices must be approved, have the matching product
// capabilities, belong to the same owner, and have an explicit access row.
func (db *DB) AuthorizeRDP(controllerID, targetID string) (bool, error) {
	if controllerID == "" || targetID == "" || controllerID == targetID {
		return false, nil
	}
	var controllerOwner, targetOwner, controllerIdentity, targetIdentity sql.NullString
	var controllerCaps, targetCaps string
	var serviceEnabled int
	err := db.QueryRow(`SELECT controller.owner_user_id, controller.identity_id, controller.approved_capabilities,
		target.owner_user_id, target.identity_id, target.approved_capabilities,
		CASE WHEN EXISTS (
			SELECT 1 FROM rdp_services service WHERE service.device_id = target.id AND service.enabled = TRUE
		) THEN 1 ELSE 0 END
		FROM devices controller
		JOIN devices target ON target.id = ?
		WHERE controller.id = ?
		  AND controller.approval_state = 'approved'
		  AND target.approval_state = 'approved'`, targetID, controllerID).
		Scan(&controllerOwner, &controllerIdentity, &controllerCaps,
			&targetOwner, &targetIdentity, &targetCaps, &serviceEnabled)
	if err != nil {
		return false, err
	}
	if !hasCapabilityJSON(controllerCaps, "rdp.controller") || !hasCapabilityJSON(targetCaps, "rdp.host") || serviceEnabled != 1 {
		return false, nil
	}
	if controllerIdentity.Valid || targetIdentity.Valid {
		if !controllerIdentity.Valid || !targetIdentity.Valid ||
			controllerIdentity.String == "" || controllerIdentity.String != targetIdentity.String {
			return false, nil
		}
		var active int
		if err := db.QueryRow(`SELECT COUNT(*) FROM identities WHERE id = ? AND status = ?`,
			controllerIdentity.String, IdentityStatusActive).Scan(&active); err != nil {
			return false, err
		}
		return active == 1, nil
	}

	// Legacy v3 behavior remains explicit, same-owner, per controller/target.
	if !controllerOwner.Valid || !targetOwner.Valid || controllerOwner.String != targetOwner.String {
		return false, nil
	}
	var granted int
	if err := db.QueryRow(`SELECT COUNT(*) FROM rdp_access_grants
		WHERE controller_device_id = ? AND target_device_id = ?`, controllerID, targetID).Scan(&granted); err != nil {
		return false, err
	}
	return granted == 1, nil
}

func hasCapabilityJSON(raw, wanted string) bool {
	var caps []string
	if json.Unmarshal([]byte(raw), &caps) != nil {
		return false
	}
	for _, cap := range caps {
		if cap == wanted {
			return true
		}
	}
	return false
}
